DaleStudy/leetcode-study

best-time-to-buy-and-sell-stock/WhiteHyun.swift, contains-duplicate/WhiteHyun.swift, two-sum/WhiteHyun.swift, valid-anagram/WhiteHyun.swift, valid-palindrome/WhiteHyun.swift
시간복잡도 $O(n^2)$로도 충분히 풀 수 있는 문제입니다.
시간복잡도 $O(n\log n)$로도 가능하리라 생각하여 정렬 후 투 포인터를 사용해서 구현해보았습니다..
> 근데 $O(n)$으로도 가능하더라고요. 😅
최소한의 가격으로 구매하고 최대한의 이익을 내는 문제입니다.
투 포인터로 구현했습니다.
`left`와 `right`를 두고 `right`를 증가시켜 최대한의 차이를 저장하다가, `right` 위치의 값이 `left`위치의 값보다 저렴한 축에 속하는 경우 `left`의 값을 `right`로 두고 다시 반복문을 진행했습니다.
Time Complexity: $O(N)$
특수문자와 숫자가 들어가는 것을 유념하고 풀어야하는 문제입니다.
Swift에서는 `Regex String`이라는 것이 있어 아래와 같이 정규식을 사용할 수 있는데요.
```swift
for match in s.matches(of: /(?<alphabet>[a-zA-Z0-9]+)/) {
// ...
}
```
컴파일 에러가 나서 [리트코드 언어 환경](https://support.leetcode.com/hc/en-us/articles/360011833974-What-are-the-environments-for-the-programming-languages)를 확인해보니 Swift 5.9 버전임을 알 수 있었습니다만..
해당 `Regex String`은 5.9에서도 가능해야하는 일이라 좀 의아해서 Support & Feedback에 [글을 …
=> [Hyun] Week 1 Solutions

best-time-to-buy-and-sell-stock/Seunghyun-Lim.java, contains-duplicate/Seunghyun-Lim.java, two-sum/Seunghyun-Lim.java, valid-anagram/Seunghyun-Lim.java, valid-palindrome/Seunghyun-Lim.java
=> [seunghyun] 1주차 답안 제출

.github/automation.yaml
https://github.com/DaleStudy/leetcode-study/pull/26#issuecomment-2079490643 에서 논의되었던 것처럼, 현재 권한 문제로 코드 작성자가 스스로 자신을 Pull Request에 Assignee로 설정할 수가 없습니다. 기여자 경험을 개선하고 관리자가 일일이 Assignee를 설정하는 수고가 없도록, GitHub Actions에 자동화 워크플로우를 추가하려고 합니다. 이 PR이 main 브랜치에 머지되면, Pull Reqeust에 Assignee가 자동으로 설정이 될 것입니다.
=> Assignee 설정 자동화

best-time-to-buy-and-sell-stock/wclee2265.cpp, contains-duplicate/wclee2265.cpp, two-sum/wclee2265.cpp, valid-anagram/wclee2265.cpp, valid-palindrome/wclee2265.cpp
=> [wclee2265] 1주차 답안 제출

best-time-to-buy-and-sell-stock/bky373.java, contains-duplicate/bky373.java, two-sum/bky373.java, valid-anagram/bky373.java, valid-palindrome/bky373.java
Java 를 사용하여 1주차 문제 풀이를 진행하였습니다.
* `1. Two Sum`
* `121. Best Time to Buy and Sell Stock`
* `125. Valid Palindrome`
* `242. Valid Anagram`
* `217. Contains Duplicate`
=> [bky373] Solutions for week 1

best-time-to-buy-and-sell-stock/Leo.py, contains-duplicate/Leo.py, two-sum/Leo.py, valid-anagram/Leo.py, valid-palindrome/Leo.py
5 solutions included;
Two Sum, Valid Anagram, Valid Palindrome, Contains Duplicate, Best Time to Buy and Sell Stock
=> [Leo] 1st Week solutions

best-time-to-buy-and-sell-stock/bhyun-kim.py, contains-duplicate/bhyun-kim.py, two-sum/bhyun-kim.py, valid-anagram/bhyun-kim.py, valid-palindrome/bhyun-kim.py
Please review the pull request for the Week 1 assignments. You can find details about the solutions in the comments within each file.
=> [bhyun-kim, bh_kim] Solution for week1 assignments

best-time-to-buy-and-sell-stock/invidam.go, contains-duplicate/invidam.go, two-sum/invidam.go, valid-anagram/invidam.go, valid-palindrome/invidam.go
- 배열을 순회하며 원소들(`appeared`)를 집합에 저장한다.
- 저장 과정에서 집합에 이미 있던 원소라면 참을 반환한다. 
- 순회가 끝났다면 모든 원소가 한 번씩만 등장한 경우이므로 거짓을 반환한다.
- 배열을 이용
- 장점: 다른 자료구조보다 가볍다.
- 단점: 동적으로 확장할 수 없다. 입력값에 의존한다.
- Hash Set을 이용
- 장점: 동적 확장이 가능하다. O(1)에 검색, 삽입이 가능하다.
- 단점: 해쉬 충돌
- Tree Set을 이용
- 장점: 크게 없음. (값들이 정렬되어 저장된다는 이점을 활용할 수 없다.)
- 단점: O(logN)의 검색, 삽입 비용.
a8669dae31ce3d187738e9867e634d12f8614d43
해시맵을 이용
시간복잡도: $O(N)$
공간복잡도: $O(N)$
- N은 배열의 크기
- 해시 맵의 크기 설정.: 2b171cce6cedfc504e237e179425c7522268fb96
- 배열의 개수만큼 맵의 크기를 설정해주니 메모리가 줄어들었다. (배열처럼 활용)
- 단, 중복 여부가 일찍 발견되는 경우 미리 크기를 할당한 이점이 줄었다.
- 이러한 결과가 속도 감소로 나타났다.
- 1/4 정도로 줄이니 메모리/시간 모두 뛰어났다.
- 일찍 발견한 경우(맵을 0으로 초기화), 모두 순회하는 경우(맵을 모두 채움)의 타협점.
- 좋은 코드 관점: 733fc966fbe05dec32b66cc8fb3cecc2508b846c
- 하나의 반복문에서 모두 처리하는 게 SRP 측면에서 바람직하지 않다.
- 반복문을 2개로 나눈다.
- 해시 셋에 모든 원소들을 넣고, …
=> [Invidam] Solve Week01 Problems (5/5) #GoLang

invert-binary-tree/dev-jonghoonpark.md, linked-list-cycle/dev-jonghoonpark.md, merge-two-sorted-lists/dev-jonghoonpark.md, reverse-linked-list/dev-jonghoonpark.md, valid-parentheses/dev-jonghoonpark.md
=> [박종훈] 2주차 답안 제출

invert-binary-tree/WhiteHyun.swift, linked-list-cycle/WhiteHyun.swift, merge-two-sorted-lists/WhiteHyun.swift, reverse-linked-list/WhiteHyun.swift, valid-parentheses/WhiteHyun.swift
- Time Complexity: $O(n)$
|ASCII 출력 확인|Swift의 `&-` 연산 과정|
|:-:|:-:|
|<img width="507" alt="Screenshot 2024-05-04 at 4 25 55 PM" src="https://github.com/DaleStudy/leetcode-study/assets/57972338/652be021-909b-4b50-b5eb-5b2d425c8da5">|![image](https://github.com/DaleStudy/leetcode-study/assets/57972338/1ea42298-27df-4123-b978-2db852d83d82)|
각 문자열을 순회하여 열린 괄호면 스택에 넣고, 닫힌 괄호면 알맞는 괄호인지 확인하고 지우는 작업으로 문제를 해결했습니다.
괄호가 알맞은지 확인하기 위해 ASCII value의 차이를 확인했습니다.
> 각 괄호별 ASCII를 출력했더니 서로 값이 최대 2차이가 나는 것을 발견했습니다.
그래서 닫힌 괄호를 발견했을 경우 ASCII값의 차이를 주어 해결했습니다.
overflow가 발생할 염려가 있어서 Swift에서 제공하는 오버플로우 연산인 `&`를 이용했습니다.
`&-`를 이용하면 뺄셈을 하되, 오버플로우를 무시합니다.
- Time Complexity: $O(n + m)$
처음에 더미 노드(dummy node)를 추가하고 첫 번째 노드와 두 번째 노드의 비교를 통해 포인터를 붙여나가는 식으로 구현했습니다. 이 과정을 …
=> [Hyun] Week 2 Solution Explanation

invert-binary-tree/Leo.py, linked-list-cycle/Leo.py, merge-two-sorted-lists/Leo.py, reverse-linked-list/Leo.py, valid-parentheses/Leo.py
=> [Leo] 2nd Week solutions

invert-binary-tree/bhyun-kim.py, linked-list-cycle/bhyun-kim.py, merge-two-sorted-lists/bhyun-kim.py, reverse-linked-list/bhyun-kim.py, valid-parentheses/bhyun-kim.py
Please refer to the comments in the file for the solution.
=> [김병현, bhyun-kim] Solution for Week2 Assignment

invert-binary-tree/bky373.java, linked-list-cycle/bky373.java, merge-two-sorted-lists/bky373.java, reverse-linked-list/bky373.java, valid-parentheses/bky373.java
- `20. Valid Parentheses`
- `206. Reverse Linked List` -> 공간 복잡도를 `O(1)` 로 할 수도 있었네요.. (주중에 새로 풀이해보고 개선해보겠습니다~)
- `226. Invert Binary Tree`
- `21. Merge Two Sorted Lists` -> 흠.. 더 좋은 방법이 있을 것 같은데 이것도 개선할 수 있으면 해보겠습니다.
- `141. Linked List Cycle`
=> [WIP][bky373] Solutions for week 2 problems

invert-binary-tree/mand2.md, linked-list-cycle/mand2.md, merge-two-sorted-lists/mand2.md, reverse-linked-list/mand2.md, valid-parentheses/mand2.md
=> [yapp][mand2] 2주차 답안 제출

invert-binary-tree/Seunghyun-Lim.java, linked-list-cycle/Seunghyun-Lim.java, merge-two-sorted-lists/Seunghyun-Lim.java, reverse-linked-list/Seunghyun-Lim.java, valid-parentheses/Seunghyun-Lim.java
1. Valid Parentheses
2. Reverse Linked List
3. Merge Two Sorted Lists
4. Linked List Cycle
5. Invert Binary Tree
현생이슈로 풀이가 많이 늦었습니다 🙏🙏
링크드 리스트에 대한 이해도가 낮아서 자료구조를 더 공부해야겠네요 ㅠㅠ
=> [seunghyun] Week 2 Solutions

invert-binary-tree/saysimple.py, linked-list-cycle/saysimple.py, merge-two-sorted-lists/saysimple.py, reverse-linked-list/saysimple.py, valid-parentheses/saysimple.py
이직 면접이 드뎌 다 끝나서 부랴부랴 제출합니다 ㅠㅠ
다음주 부터는 여유롭지 않을까... 라는 헛된 기대를 하는 중입니다. ㅋㅋ
=> [saysimple] 2주차 문제 풀이입니다.

invert-binary-tree/han.exs, linked-list-cycle/han.rb, merge-two-sorted-lists/han.exs, reverse-linked-list/han.exs, valid-parentheses/han.exs
다음주엔 더 빨리 제출 할 수 있도록 하겠습니다 ^^;
linked-list-cycle 문제는 왜 인진 모르겠으나 leet code에 elixir 선택이 불가능해서 제일 익숙한 언어인 ruby로 풀었습니다.
=> [김한기] Week 2 solutions

scripts/common.bash
- `.env` 파일 생성을 처리하는 `setup_env_file` 함수를 추가했습니다.
- `.env`가 없음에도 스크립트가 실행되는 오류를 수정했습니다.
처음에 `.env` 파일 설정의 귀찮음을 해결하고자 스크립트를 실행하면 알아서 파일을 만들고 언어 선택까지 자동화하도록 구현해보았습니다.
사용자가 선택할 수 있는 언어 목록을 번호로 입력받도록 설정했습니다(입력이 없는 경우 기본 언어는 `python3`로 설정됩니다)
선택한 언어는 사용자의 닉네임과 함께 `.env` 파일에 저장됩니다.
`.env` 파일이 없는 경우 설정 과정으로 안내하여 사용자 경험을 개선했습니다.
|시연 영상|
|:-:|
|![Screen Recording 2024-05-12 at 6 12 49 PM](https://github.com/DaleStudy/leetcode-study/assets/57972338/a2f8caca-863e-434d-a3bc-69d3d6335b39)|
- `.env` 파일이 없는 상태에서 스크립트를 테스트하여 설정 과정을 확인했습니다.
- 사용자 입력 및 기본값으로 `.env` 파일 생성을 검증했습니다.
- 유효한 입력과 유효하지 않은 입력을 통해 언어 선택 기능을 테스트했습니다.
- 생성된 `.env` 파일에서 환경 변수 로딩을 확인했습니다.
---
리뷰해주시고 피드백 또는 제안사항을 주시면 감사하겠습니다. 🙇
=> [FEAT] .env 파일 처리 개선 및 언어 선택 기능 추가

climbing-stairs/bky373.java, maximum-depth-of-binary-tree/bky373.java, meeting-rooms/bky373.java, same-tree/bky373.java, subtree-of-another-tree/bky373.java
* `104. Maximum Depth of Binary Tree`
* `100. Same Tree`
* `572. Subtree of Another Tree`
* `70. Climbing Stairs`
* `252. Meeting Rooms`
=> [bky373] Week 3 Solutions

climbing-stairs/han.exs, maximum-depth-of-binary-tree/han.exs, same-tree/han.exs, subtree-of-another-tree/han.exs
지각이네요 ^^;
그리고 마지막 문제는 풀지 못했습니다 ㅠㅠ
이번주에도 엘릭서로 풀었는데
약간의 특이사항은 이번주 문제에 두개의 트리가 동일한지 비교하는 문제가 두개 나왔는데,
엘릭서는 함수형 언어이고, 모든 객체(?)가 한번만들어지면 불변이므로, 무언가를 비교할때 모든건 불변한다는걸 이용해서 그 값을 비교한다는 특징이 있고... 이때문에 문제가 너무나도 쉽게 풀릴 수 있었네요.
예를들어 same tree 문제는 `p == q` 이렇게만 해도 같은지 비교가 가능한...
(최소한 루비 기준에선)다른 언어에선 두 객체가 있고, `Object.new == Object.new` 이와같이 하면 객체의 레퍼런스가 같은지 비교하는데, 
다른 언어에선 주소값을 비교하는 이유와 엘릭서가 그렇게 동작하지 않는 이유를 추측해본다면
다른 언어들은 다른 쓰레드에서 값이 언제라도 바뀔 수 있기때문에 레퍼런스가 같은지 비교하고, 엘릭서는 두 객체가 한번 만들어지면 절대 변할 일 없기때문에 좀더 자신있게 값 전체를 비교하는 식으로 되어있지 않나 싶네요... 레퍼런스 비교대신에...
맞나 모르겠습니다...
=> Week 3 solutions

climbing-stairs/invidam.go.md, maximum-depth-of-binary-tree/invidam.go.md, meeting-rooms/invidam.go.md, same-tree/invidam.go.md, subtree-of-another-tree/invidam.go.md
3주차 제출합니다!
가능한 영어로 설명 작성하려 하고 있는데, 하다보니 느는 게 보여 재밌네요. (지피티의 피드백이 정말 매서워요...)
고랭은 익히면 익힐수록 복잡하지만 몰랐던 점들 많이 배우고 있는 것 같아요!
=> [Vidam] Week 3 Solution | Go

climbing-stairs/yolophg.js, maximum-depth-of-binary-tree/yolophg.js, meeting-rooms/yolophg.js, same-tree/yolophg.js, subtree-of-another-tree/yolophg.js
Included as follows :
- Maximum Depth of Binary Tree
- Same Tree
- Subtree of Another Tree
- Climbing Stairs
- Meeting Rooms
=> [Helena] Week 3 solutions

climbing-stairs/saysimple.py, maximum-depth-of-binary-tree/saysimple.py, meeting-rooms/saysimple.py, same-tree/saysimple.py, subtree-of-another-tree/saysimple.py
=> [saysimple] 3주차 문제 풀이

counting-bits/WhiteHyun.swift, group-anagrams/WhiteHyun.swift, missing-number/WhiteHyun.swift, number-of-1-bits/WhiteHyun.swift, reverse-bits/WhiteHyun.swift
- Time Complexity: $O(n * m log m)$ (m = string length, n = string array's length)
1. 처음 접근할 때 단순히 Set 타입으로 묶어 Dictionary의 key값으로 제공함
2. `"good"`과 `"god"`이 같이 묶이는 문제점을 발견
3. Set 대신에 정렬된 배열값을 key로 하여 Dictionary에 추가
- [Test code](https://github.com/WhiteHyun/Algorithm-Journey/blob/main/swift/AlgorithmTests/LeetCode/LeetCode49Tests.swift)
- Time Complexity: $O(1)$
1. 처음에 두 가지의 접근 방식이 떠오름
a. 2진수를 문자열로 변환 → 문자열을 거꾸로 변환 → prefix가 0이어서 축약된 길이만큼 suffix에 0을 확장 → 정수타입으로 변환 및 리턴
b. 각 비트마다 쉬프트 연산(`<<`, `>>`)과 앤드 연산(`&`)을 활용하여 더하고 리턴
2. 전부 구현하고 시간차를 확인해보았으나, 32자리수를 처리하는 것에 대해 시간 계산은 유의미한 차이를 찾지 못함
- [Test code](https://github.com/WhiteHyun/Algorithm-Journey/blob/main/swift/AlgorithmTests/LeetCode/LeetCode190Tests.swift)
- Time Complexity: $O(1)$
- …
=> [Hyun] Week 4 Solution Explanation

counting-bits/invidam.go.md, group-anagrams/invidam.go.md, missing-number/invidam.go.md, number-of-1-bits/invidam.go.md
> [!CAUTION]
> 시간 투자를 많이 못했어서, 리뷰 (꼼꼼히) 안해주셔도 괜찮아요!
4주차 풀이 올립니다. **졸업작품 마감 기간이라 시간을 많이 못 쏟았어요.** 꼼꼼히 신경 못 쓴 부분이 많을 것이고 리뷰해주시는 데 불편함이 있을까봐 리뷰 안해주셔도 저는 괜찮습니다. (이번 주차 의의는 바쁜 와중에도 루틴을 지키자 였어서요.)
요즘 신경 못 쓴 만큼 다음 주 부터는 더더욱 열심히 하겠습니다!
=> [Vidam, Invidam] Week 4 Solution

counting-bits/Leo.py, group-anagrams/Leo.py, missing-number/Leo.py, number-of-1-bits/Leo.py, reverse-bits/Leo.py
=> [Leo] 4th Week solutions

counting-bits/yolophg.js, group-anagrams/yolophg.js, missing-number/yolophg.js, number-of-1-bits/yolophg.js, reverse-bits/yolophg.js
- Number of 1 Bits
- Counting Bits
- Reverse Bits
- Missing Number
- Group Anagrams
=> [Helena] Week 4 solutions

counting-bits/dev-jonghoonpark.md, group-anagrams/dev-jonghoonpark.md, missing-number/dev-jonghoonpark.md, number-of-1-bits/dev-jonghoonpark.md, reverse-bits/dev-jonghoonpark.md
=> [박종훈] 4주차 답안 제출

counting-bits/saysimple.py, group-anagrams/saysimple.py, missing-number/saysimple.py, number-of-1-bits/saysimple.py, reverse-bits/saysimple.py
=> Saysimple week4

3sum/nhistory.js, encode-and-decode-strings/nhistory.js, longest-consecutive-sequence/nhistory.js, product-of-array-except-self/nhistory.js, top-k-frequent-elements/nhistory.js
- Top K Frequent Elements
- Encode and Decode Strings
- Product of Array Except Self (added 5/27)
- Longest Consecutive Sequence (added 5/28)
- 3sum (added 5/30)
=> [Sehwan]Week5 solutions with javascript

3sum/dev-jonghoonpark.md, encode-and-decode-strings/dev-jonghoonpark.md, longest-consecutive-sequence/dev-jonghoonpark.md, product-of-array-except-self/dev-jonghoonpark.md, top-k-frequent-elements/dev-jonghoonpark.md
5주차 답안 제출합니다.
---
- 블로그 링크 : https://algorithm.jonghoonpark.com/2024/04/18/leetcode-347
- 블로그 링크 : https://algorithm.jonghoonpark.com/2024/05/29/leetcode-271
- 블로그 링크 : https://algorithm.jonghoonpark.com/2024/05/08/leetcode-238
- 블로그 링크 : https://algorithm.jonghoonpark.com/2024/05/28/leetcode-128
- 블로그 링크 : https://algorithm.jonghoonpark.com/2024/05/07/leetcode-15
=> [박종훈] 5주차 답안 제출

3sum/yolophg.js, encode-and-decode-strings/yolophg.js, longest-consecutive-sequence/yolophg.js, product-of-array-except-self/yolophg.js, top-k-frequent-elements/yolophg.js
- Top K Frequent Elements
- Encode and Decode Strings
- Product of Array Except Self
- Longest Consecutive Sequence
- 3Sum
=> [Helena] Week 5 solutions

container-with-most-water/dev-jonghoonpark.md, find-minimum-in-rotated-sorted-array/dev-jonghoonpark.md, longest-repeating-character-replacement/dev-jonghoonpark.md, longest-substring-without-repeating-characters/dev-jonghoonpark.md, search-in-rotated-sorted-array/dev-jonghoonpark.md
문제: https://leetcode.com/problems/container-with-most-water/
풀이: https://algorithm.jonghoonpark.com/2024/06/02/leetcode-11
문제: https://leetcode.com/problems/longest-substring-without-repeating-characters/
풀이: https://algorithm.jonghoonpark.com/2024/02/18/leetcode-3
문제: https://leetcode.com/problems/longest-repeating-character-replacement/
풀이: https://algorithm.jonghoonpark.com/2024/04/29/leetcode-424
문제: https://leetcode.com/problems/find-minimum-in-rotated-sorted-array/
풀이: https://algorithm.jonghoonpark.com/2024/06/03/leetcode-153
문제: https://leetcode.com/problems/search-in-rotated-sorted-array/
풀이: https://algorithm.jonghoonpark.com/2024/06/03/leetcode-33
=> [박종훈] 6주차 답안 제출

3sum/bky373.java, encode-and-decode-strings/bky373.java, longest-consecutive-sequence/bky373.java, product-of-array-except-self/bky373.java, top-k-frequent-elements/bky373.java
- [3Sum](https://leetcode.com/problems/3sum/)
- [Encode and Decode Strings](https://leetcode.com/problems/encode-and-decode-strings/)
- [Longest Consecutive Sequence](https://leetcode.com/problems/longest-consecutive-sequence/)
- [Product of Array Except Self](https://leetcode.com/problems/product-of-array-except-self/)
- [Top K Frequent Elements](https://leetcode.com/problems/top-k-frequent-elements/)
=> [bky373] Solve week 5 problems

container-with-most-water/yolophg.js, find-minimum-in-rotated-sorted-array/yolophg.js, longest-repeating-character-replacement/yolophg.js, longest-substring-without-repeating-characters/yolophg.js, search-in-rotated-sorted-array/yolophg.js
- Container With Most Water
- Longest Substring Without Repeating Characters
- Longest Repeating Character Replacement
- Find Minimum In Rotated Sorted Array
- Search In Rotated Sorted Array
=> [Helena] Week 6 solutions

container-with-most-water/nhistory.js, find-minimum-in-rotated-sorted-array/nhistory.js, longest-repeating-character-replacement/nhistory.js, longest-substring-without-repeating-characters/nhistory.js, search-in-rotated-sorted-array/nhistory.js
=> [Sehwan] Week6 solutions with javascript

container-with-most-water/WhiteHyun.swift, find-minimum-in-rotated-sorted-array/WhiteHyun.swift, longest-repeating-character-replacement/WhiteHyun.swift, longest-substring-without-repeating-characters/WhiteHyun.swift, search-in-rotated-sorted-array/WhiteHyun.swift
- Time Complexity: $O(n)$
투 포인터를 활용해서 문제를 풀었습니다.
left, right를 각각 배열의 첫 번째, 마지막 요소에 접근할 수 있는 인덱스로 설정한 뒤
두 사이의 넓이(`(right - left) * min(height[left], height[right])`)를 구하고 정답 변수에 최댓값을 설정하는 방식으로 구현했습니다.
그 중에서 height[left]와 height[right] 중 가장 작은 값을 가진 포인터를 찾아 가감시켜가면서 값을 조절했습니다.
- [Test code](https://github.com/WhiteHyun/Algorithm-Journey/blob/main/swift/AlgorithmTests/LeetCode/LeetCode11Tests.swift)
- Time Complexity: $O(n)$
문자열을 배열로 만들고, 앞으로 substring값을 임시저장할 Set타입을 만든 뒤 각 문자를 확인해나가며 긴 longest substring을 체크했습니다.
> [!Tip]
>
> Q: 여기서 잠깐! 문자열을 왜 배열로 만드셨나요?
> A: Swift의 문자열 처리가 꽤나 느리기 때문에, 문자열을 배열로 초기화해준 뒤 Int값의 index로 배열에 접근하는 것이 시간 효율에 좋습니다.
> 참고로 Swift의 `String`타입은 Int타입으로 인덱스 접근이 되지 않습니다. ㅎㅎ..
- [Test …
=> [Hyun] Week 6 Solution Explanation

container-with-most-water/invidam.go.md, find-minimum-in-rotated-sorted-array/invidam.go.md, longest-repeating-character-replacement/invidam.go.md, longest-substring-without-repeating-characters/invidam.go.md, search-in-rotated-sorted-array/invidam.go.md
=> [Invidam] Week 06 Solutions

container-with-most-water/bky373.java, find-minimum-in-rotated-sorted-array/bky373.java, longest-repeating-character-replacement/bky373.java, longest-substring-without-repeating-characters/bky373.java, search-in-rotated-sorted-array/bky373.java
- [Search In Rotated Sorted Array	
](https://leetcode.com/problems/search-in-rotated-sorted-array/)
- [Longest Substring Without Repeating Characters](https://leetcode.com/problems/longest-substring-without-repeating-characters/)
- [Find Minimum In Rotated Sorted Array	
](https://leetcode.com/problems/find-minimum-in-rotated-sorted-array/)
- [Container With Most Water	
](https://leetcode.com/problems/container-with-most-water/solution/)
- [Longest Repeating Character Replacement	
](https://leetcode.com/problems/longest-repeating-character-replacement/)
=> [bky373] Week 6 Solutions

binary-tree-level-order-traversal/dev-jonghoonpark.md, lowest-common-ancestor-of-a-binary-search-tree/dev-jonghoonpark.md, remove-nth-node-from-end-of-list/dev-jonghoonpark.md, reorder-list/dev-jonghoonpark.md, validate-binary-search-tree/dev-jonghoonpark.md
문제: https://leetcode.com/problems/reorder-list/
풀이: https://algorithm.jonghoonpark.com/2024/06/10/leetcode-143
문제: https://leetcode.com/problems/remove-nth-node-from-end-of-list/
풀이: https://algorithm.jonghoonpark.com/2024/06/10/leetcode-19
문제: https://leetcode.com/problems/lowest-common-ancestor-of-a-binary-search-tree/
풀이: https://algorithm.jonghoonpark.com/2024/06/10/leetcode-235
문제: https://leetcode.com/problems/binary-tree-level-order-traversal/
풀이: https://algorithm.jonghoonpark.com/2024/06/10/leetcode-102
문제: https://leetcode.com/problems/validate-binary-search-tree/
풀이: https://algorithm.jonghoonpark.com/2024/06/10/leetcode-98
=> [박종훈] 7주차 답안 제출

binary-tree-level-order-traversal/nhistory.js, lowest-common-ancestor-of-a-binary-search-tree/nhistory.js, remove-nth-node-from-end-of-list/nhistory.js, reorder-list/nhistory.js, validate-binary-search-tree/nhistory.js
- Reorder List
- Remove Nth Node From End of List
- Lowest Common Ancestor of a Binary Search Tree
- Binary Tree Level Order Traversal
- Validate Binary Search Tree
=> [Sehwan] Week7 solution with JavaScript

binary-tree-level-order-traversal/WhiteHyun.swift, lowest-common-ancestor-of-a-binary-search-tree/WhiteHyun.swift, remove-nth-node-from-end-of-list/WhiteHyun.swift, reorder-list/WhiteHyun.swift, validate-binary-search-tree/WhiteHyun.swift
- Time Complexity: $O(n)$
|기존 리스트|수정해야할 리스트|
|:-:|:-:|
|![image](https://github.com/DaleStudy/leetcode-study/assets/57972338/fedb80af-37ea-495c-b218-2ccbd462e268)|![image](https://github.com/DaleStudy/leetcode-study/assets/57972338/a954138b-88fb-46bb-b092-dbc248dc70a6)|
처음에는 하나의 메서드를 활용해서 재귀로 돌릴 수 있을까 고민했지만 아직 제 머리로는 명확하게 구상하지 못해 while문과 for문을 이용하여 풀이했습니다.
위 그림처럼 각 노드의 `next`를 달팽이처럼 연결지어줘야하기 때문에, `head`부터 `tail`까지를 반복하며 리스트에 넣어주었습니다.
그 뒤, 리스트에 들어간 각 노드들을 index로 접근하여 `next`에 값을 알맞게 수정해주었습니다.
이렇게 `next`를 설정하다보면 마지막에 자기 자신을 참조하게 되는 경우가 발생하는데, 조건식을 통해 자기 자신으로 할당이 될 경우를 판단하여 `null`로 설정해주었습니다.
홀수인 경우에는 반복문에서 따로 처리되지 않기 때문에 추가로 `next`를 `null`로 설정해주는 코드를 넣었습니다.
- [143. Reorder List - Test code](https://github.com/WhiteHyun/Algorithm-Journey/blob/main/swift/AlgorithmTests …
=> [Hyun] Week 7 Solution Explanation

combination-sum/dev-jonghoonpark.md, construct-binary-tree-from-preorder-and-inorder-traversal/dev-jonghoonpark.md, implement-trie-prefix-tree/dev-jonghoonpark.md, kth-smallest-element-in-a-bst/dev-jonghoonpark.md, word-search/dev-jonghoonpark.md
- 문제: https://leetcode.com/problems/kth-smallest-element-in-a-bst/
- 풀이: [https://algorithm.jonghoonpark.com/2024/06/23/leetcode-230](https://algorithm.jonghoonpark.com/2024/06/23/leetcode-230)
- 문제: https://leetcode.com/problems/construct-binary-tree-from-preorder-and-inorder-traversal/
- 풀이: [https://algorithm.jonghoonpark.com/2024/06/23/leetcode-105](https://algorithm.jonghoonpark.com/2024/06/23/leetcode-105)
- 문제: https://www.algodale.com/problems/combination-sum/
- 풀이: [https://algorithm.jonghoonpark.com/2024/06/23/leetcode-39](https://algorithm.jonghoonpark.com/2024/06/23/leetcode-39)
- 문제: https://leetcode.com/problems/word-search/
- 풀이: [https://algorithm.jonghoonpark.com/2024/06/23/leetcode-79
](https://algorithm.jonghoonpark.com/2024/06/23/leetcode-79
)
- 문제: …
=> [박종훈] 8주차 답안 제출

binary-tree-level-order-traversal/bky373.java, lowest-common-ancestor-of-a-binary-search-tree/bky373.java, remove-nth-node-from-end-of-list/bky373.java, reorder-list/bky373.java, validate-binary-search-tree/bky373.java
- 시간이 밀리다 보니 요번 주차는 풀이에 시간을 많이 할애하지 못했네요ㅠㅠ 이번 주차는 솔루션 도움을 많이 받았는데 이후에 한 번 더 풀이해보는 시간 갖도록 하겠습니다!
=> [bky373] Solve 7th week problems

combination-sum/yolophg.js, construct-binary-tree-from-preorder-and-inorder-traversal/yolophg.js, implement-trie-prefix-tree/yolophg.js, kth-smallest-element-in-a-bst/yolophg.js, word-search/yolophg.js
- Kth Smallest Element In a Bst
- Construct Binary Tree From Preorder And Inorder Traversal
- Combination Sum
- Word Search
- Implement Trie Prefix Tree
=> [Helena] Week 8 solutions

combination-sum/WhiteHyun.swift, construct-binary-tree-from-preorder-and-inorder-traversal/WhiteHyun.swift, implement-trie-prefix-tree/WhiteHyun.swift, kth-smallest-element-in-a-bst/WhiteHyun.swift, word-search/WhiteHyun.swift
- Time Complexity: $O(n)$
- Space Complexity: $O(log n)$
왼쪽 자식노드 -> 자신 -> 오른쪽 자식 노드로 순차 확인하는 느낌으로 접근하여 재귀적으로 처리했습니다.
- [230. Kth Smallest Element in a BST - Test code](https://github.com/WhiteHyun/Algorithm-Journey/blob/main/swift/AlgorithmTests/LeetCode/Medium/LeetCode230Tests.swift)
- Time Complexity: $O(n)$
꽤나 생각을 요했던 문제여서 재밌게 풀었습니다 ㅎㅎ DaleSeo님의 글을 많이 참고했네요 ☺️
preorder: root -> left -> right
inorder: left -> root -> right
위 특성에 맞게 preorder의 첫 번째 값이 inorder에 어디에 위치하는지에 따라서 left와 right 리프노드를 처리할 수 있습니다. 이런 특성을 통해 문제를 재귀적으로 풀이했습니다.
- [105. Construct Binary Tree from Preorder and Inorder Traversal - Test code](https://github.com/WhiteHyun/Algorithm-Journey/blob/main/swift/AlgorithmTests/LeetCode/Medium/LeetCode105Tests.swift)
- Time Complexity: $O(2^n)$
- Space …
=> [Hyun] Week 8 Solution Explanation

clone-graph/yolophg.js, combination-sum/yolophg.js, construct-binary-tree-from-preorder-and-inorder-traversal/yolophg.js, course-schedule/yolophg.js, design-add-and-search-words-data-structure/yoloophg.js, implement-trie-prefix-tree/yolophg.js, kth-smallest-element-in-a-bst/yolophg.js, number-of-islands/yolophg.js, pacific-atlantic-water-flow/yolophg.js, word-search/yolophg.js
- Design Add And Search Words Data Structure
- Number of Islands
- Clone Graph 
- Pacific Atlantic Water Flow 
- Course Schedule
=> [Helena] Week 9 solutions

clone-graph/dev-jonghoonpark.md, course-schedule/dev-jonghoonpark.md, design-add-and-search-words-data-structure/dev-jonghoonpark.md, number-of-islands/dev-jonghoonpark.md, pacific-atlantic-water-flow/dev-jonghoonpark.md
- 문제: https://leetcode.com/problems/design-add-and-search-words-data-structure/
- 풀이: [https://algorithm.jonghoonpark.com/2024/06/30/leetcode-211](https://algorithm.jonghoonpark.com/2024/06/30/leetcode-211)
- 문제: https://leetcode.com/problems/number-of-islands/
- 풀이: https://algorithm.jonghoonpark.com/2024/03/31/leetcode-200
- 문제: https://leetcode.com/problems/clone-graph/
- 풀이: https://algorithm.jonghoonpark.com/2024/02/13/leetcode-133
- 문제: https://leetcode.com/problems/pacific-atlantic-water-flow/
- 풀이: https://algorithm.jonghoonpark.com/2024/03/03/leetcode-417
- 문제: https://leetcode.com/problems/course-schedule/
- 풀이: https://algorithm.jonghoonpark.com/2024/03/01/leetcode-207
=> [박종훈] 9주차 답안 제출 

clone-graph/invidam.go.md, course-schedule/invidam.go.md, design-add-and-search-words-data-structure/invidam.go.md, number-of-islands/invidam.go.md, pacific-atlantic-water-flow/invidam.go.md
9주차 미션 제출합니다!
복잡도와 코드만 간단히 작성했어요 ㅎㅎ..
=> [Invidam] Week 09 Solutions

combination-sum/bky373.java, construct-binary-tree-from-preorder-and-inorder-traversal/bky373.java, implement-trie-prefix-tree/bky373.java, kth-smallest-element-in-a-bst/bky373.java, word-search/bky373.java
한 주 다가가면 한 주 멀어지는.. ㅠㅠ 9주차, 10주차는 좀더 빨리 올려보겠습니다.
=> [bky373] 8th Week Solutions

clone-graph/bky373.java, course-schedule/bky373.java, design-add-and-search-words-data-structure/bky373.java, number-of-islands/bky373.java, pacific-atlantic-water-flow/bky373.java
10주차 전까지 두 번의 고비가 있군요 
이 9부 능선을 넘고 다시 흐름을 타보겠습니다..
=> [bky373] 9th Week Soultions

graph-valid-tree/dev-jonghoonpark.md, house-robber-ii/dev-jonghoonpark.md, house-robber/dev-jonghoonpark.md, longest-palindromic-substring/dev-jonghoonpark.md, number-of-connected-components-in-an-undirected-graph/dev-jonghoonpark.md
- 문제
- 유료: https://leetcode.com/problems/graph-valid-tree/
- 무료: https://www.lintcode.com/problem/178/
- 풀이: https://algorithm.jonghoonpark.com/2024/07/02/leetcode-261
- 문제
- 유료: https://leetcode.com/problems/number-of-connected-components-in-an-undirected-graph/
- 무료: https://www.lintcode.com/problem/3651/
- 풀이: https://algorithm.jonghoonpark.com/2024/07/03/leetcode-323
- 문제: https://leetcode.com/problems/house-robber/
- 풀이: https://algorithm.jonghoonpark.com/2024/07/03/leetcode-198
- 문제: https://leetcode.com/problems/house-robber-ii/
- 풀이: https://algorithm.jonghoonpark.com/2024/07/03/leetcode-213
- 문제: https://leetcode.com/problems/longest-palindromic-substring/
- 풀이: https://algorithm.jonghoonpark.com/2024/07/01/leetcode-5
=> [박종훈] 10주차 답안 제출

graph-valid-tree/yolophg.js, house-robber-ii/yolophg.js, house-robber/yolophg.js, longest-palindromic-substring/yolophg.js, number-of-connected-components-in-an-undirected-graph/yolophg.js
- Graph Valid Tree
- Number of Connected Components in an Undirected Graph
- House Robber
- House Robber II
- Longest Palindromic Substring
=> [Helena] Week 10 solutions

graph-valid-tree/bky373.java, house-robber-ii/bky373.java, house-robber/bky373.java, longest-palindromic-substring/bky373.java, number-of-connected-components-in-an-undirected-graph/bky373.java
- 문제
- 유료: https://leetcode.com/problems/graph-valid-tree/
- 무료: https://www.lintcode.com/problem/178/
- 풀이: https://www.algodale.com/problems/graph-valid-tree/
- 위치: https://github.com/DaleStudy/leetcode-study/tree/main/graph-valid-tree
- 문제
- 유료: https://leetcode.com/problems/number-of-connected-components-in-an-undirected-graph/
- 무료: https://www.lintcode.com/problem/3651/
- 풀이: https://www.algodale.com/problems/number-of-connected-components-in-an-undirected-graph/
- 위치: https://github.com/DaleStudy/leetcode-study/tree/main/number-of-connected-components-in-an-undirected-graph
- 문제: https://leetcode.com/problems/house-robber/
- 풀이: https://www.algodale.com/problems/house-robber/
- 위치: https://github.com/DaleStudy/leetcode-study/tree/main/house-robber
- 문제: …
=> [bky373] 10th week solutions

coin-change/WhiteHyun.swift, decode-ways/WhiteHyun.swift, maximum-product-subarray/WhiteHyun.swift, palindromic-substrings/WhiteHyun.swift, word-break/WhiteHyun.swift
- Time Complexity: $O(N^2)$
처음에는 Brute Force로 풀이( $O(N^3)$ )했으나 꽤나 시간이 많이 소모되는 것을 확인하였고, 더 나은 방안을 고려해보기로 했습니다.
이전 문제 [5. Longest Palindromic Substring](https://leetcode.com/problems/longest-palindromic-substring/)에서 팰린드롬이 될 문자열의 중간에서 시작하여 양옆으로 뻗어나가는 풀이법에 착안하여 $O(N^2)$ 으로 풀이할 수 있었습니다.
- Time Complexity: $O(N)$
이번 문제는 풀이법을 도출하는 게 어려웠네요.
Memoization을 이용한 풀이, 그리고 dp를 활용한 풀이 두 가지 방식으로 시도해보았습니다.
- Time Complexity: $O(N * Amount)$
- Space Complexity: $O(Amount)$
단순 그리디 문제인줄 알고 풀었으나 [1, 5, 7]이고 amount가 25인 경우 제일 적은 동전의 수는 값어치가 5인 동전을 5번 사용하는 것이기 때문에, 제일 큰 값 위주로 처리해서는 안 된다는 걸 깨달았습니다.
따라서 제일 적은 개수를 구하고자 DP를 활용했습니다. 동전의 값어치를 `coin`으로 하고 특정 금액에 한하여 점화식을 다음과 같이 $F(n) = MIN(F(n), F(n - coin) + 1)$ 로 세워서 풀이했습니다.
- Time Complexity: $O(N)$
- Space …
=> [Hyun] Week 11 Solution Explanation

coin-change/dev-jonghoonpark.md, decode-ways/dev-jonghoonpark.md, maximum-product-subarray/dev-jonghoonpark.md, palindromic-substrings/dev-jonghoonpark.md, word-break/dev-jonghoonpark.md
- 문제: https://leetcode.com/problems/palindromic-substrings/
- 풀이: https://algorithm.jonghoonpark.com/2024/07/08/leetcode-647
- 문제: https://leetcode.com/problems/decode-ways/
- 풀이: https://algorithm.jonghoonpark.com/2024/07/08/leetcode-91
- 문제: https://leetcode.com/problems/coin-change/
- 풀이: https://algorithm.jonghoonpark.com/2024/02/26/leetcode-322
- 문제: https://leetcode.com/problems/maximum-product-subarray/
- 풀이: https://algorithm.jonghoonpark.com/2024/07/09/leetcode-152
- 문제: https://leetcode.com/problems/word-break/
- 풀이: https://algorithm.jonghoonpark.com/2024/02/28/leetcode-139
=> [박종훈] 11주차 답안 제출

coin-change/yolophg.js, decode-ways/yolophg.js, maximum-product-subarray/yolophg.js, palindromic-substrings/yolophg.js, word-break/yolophg.js
- Palindromic Substrings
- Decode Ways
- Coin Change
- Maximum Product Subarray
- Word Break
=> [Helena] Week 11 solutions

jump-game/WhiteHyun.swift, longest-common-subsequence/WhiteHyun.swift, longest-increasing-subsequence/WhiteHyun.swift, maximum-subarray/WhiteHyun.swift, unique-paths/WhiteHyun.swift
- Time Complexity: $O(N log N)$
- Space Complexity: $O(N)$
처음에는 [DP로 풀었으나](https://gist.github.com/WhiteHyun/b2344c0fa3425cd5333d1a2a32498d37), 이분탐색(Binary Search)으로 개선했습니다.
처음에는 첫 번째 요소를 `tails`라는 `lis`배열에 넣고 그 뒤부터 각 요소를 비교합니다.
tails의 마지막값보다 주어진 number가 큰 경우 lis배열인 `tails`가 더 길어질 수 있기에, `tails`배열 바로 뒤에 number를 추가합니다.
만약 그러지 않다면, `tails`의 어느 부분에 적절하게 들어갈 수 있도록 `Binary Search`로 인덱스를 구합니다.
이 방법은 실제 LIS 수열을 구성하지 않고 길이만을 효율적으로 계산합니다.
- Time Complexity: $O(NM)$
- Space Complexity: $O(NM)$
로봇의 위치서부터 위아래는 전부 1로 설정하고, 로봇의 남동쪽 대각선 한칸부터 dp를 시작하여 풀이했습니다.
- Time Complexity: $O(NM)$
- Space Complexity: $O(NM)$
사고를 확장하는 게 좀 어려웠습니다. 🥲 알고달레 풀이 보고 해결했습니다.
- Time Complexity: $O(N)$
다음 것을 더한 것과 다음 값 자체의 크기 관계를 비교하여 풀이했습니다.
- Time Complexity: $O(N)$
생각의 …
=> [Hyun] Week 12 Solution Explanation

jump-game/dev-jonghoonpark.md, longest-common-subsequence/dev-jonghoonpark.md, longest-increasing-subsequence/dev-jonghoonpark.md, maximum-subarray/dev-jonghoonpark.md, unique-paths/dev-jonghoonpark.md
- 문제: https://leetcode.com/problems/longest-increasing-subsequence/
- 풀이: https://algorithm.jonghoonpark.com/2024/02/27/leetcode-300
- 문제: https://leetcode.com/problems/unique-paths/
- 풀이: https://algorithm.jonghoonpark.com/2024/07/16/leetcode-62
- 문제: https://leetcode.com/problems/longest-common-subsequence/
- 풀이: https://algorithm.jonghoonpark.com/2024/07/17/leetcode-1143
- 문제: https://leetcode.com/problems/maximum-subarray/
- 풀이: https://algorithm.jonghoonpark.com/2024/05/07/leetcode-53
- 문제: https://leetcode.com/problems/jump-game/
- 풀이: https://algorithm.jonghoonpark.com/2024/07/17/leetcode-55
=> [박종훈] 12주차 답안 제출

coin-change/bky373.java, decode-ways/bky373.java, maximum-product-subarray/bky373.java, palindromic-substrings/bky373.java, word-break/bky373.java
DP는 아직 많이 취약하네요 ㅠㅠ 재수 때 분발해보겠습니다
=> [bky373] Add Week 11 Solutions

jump-game/yolophg.js, longest-common-subsequence/yolophg.js, longest-increasing-subsequence/yolophg.js, maximum-subarray/yolophg.js, unique-paths/yolophg.js
- Longest Increasing Subsequence
- Unique Paths
- Longest Common Subsequence
- Maximum Subarray
- Jump Game
=> [Helena] Week 12 solutions 

coin-change/bky373.java, decode-ways/bky373.java, jump-game/bky373.java, longest-common-subsequence/bky373.java, longest-increasing-subsequence/bky373.java, maximum-product-subarray/bky373.java, maximum-subarray/bky373.java, palindromic-substrings/bky373.java, unique-paths/bky373.java, word-break/bky373.java
- 문제: https://leetcode.com/problems/longest-increasing-subsequence/
- 문제: https://leetcode.com/problems/unique-paths/
- 문제: https://leetcode.com/problems/longest-common-subsequence/
- 문제: https://leetcode.com/problems/maximum-subarray/
- 문제: https://leetcode.com/problems/jump-game/
=> [bky373] Add Week 12 Solutions

insert-interval/yolophg.js, meeting-rooms-ii/yolophg.js, merge-intervals/yolophg.js, non-overlapping-intervals/yolophg.js, rotate-image/yolophg.js
- Insert Interval
- Merge Intervals
- Non Overlapping Intervals
- Meeting Rooms II
- Rotate Image
=> [Helena] Week 13 solutions

insert-interval/dev-jonghoonpark.md, meeting-rooms-ii/dev-jonghoonpark.md, merge-intervals/dev-jonghoonpark.md, non-overlapping-intervals/dev-jonghoonpark.md, rotate-image/dev-jonghoonpark.md
- 문제: https://leetcode.com/problems/insert-interval/
- 풀이: https://algorithm.jonghoonpark.com/2024/02/14/leetcode-57
- 문제: https://leetcode.com/problems/merge-intervals/
- 풀이: https://algorithm.jonghoonpark.com/2024/07/23/leetcode-56
- 문제: https://leetcode.com/problems/non-overlapping-intervals/
- 풀이: https://algorithm.jonghoonpark.com/2024/07/23/leetcode-435
- 문제: 
- 유료: https://leetcode.com/problems/meeting-rooms-ii/
- 무료: https://www.lintcode.com/problem/919/
- 풀이: https://algorithm.jonghoonpark.com/2024/07/22/leetcode-253
- 문제: https://leetcode.com/problems/rotate-image/
- 풀이: https://algorithm.jonghoonpark.com/2024/07/22/leetcode-48
=> [박종훈] 13주차 답안 제출

set-matrix-zeroes/yolophg.js, spiral-matrix/yolophg.js, sum-of-two-integers/yolophg.js
- Spiral Matrix
- Set Matrix Zeroes
- Sum of Two Integers
=> [Helena] Week 14 solutions

contains-duplicate/TonyKim9401.java, kth-smallest-element-in-a-bst/TonyKim9401.java, number-of-1-bits/TonyKim9401.java, palindromic-substrings/TonyKim9401.java, top-k-frequent-elements/TonyKim9401.java
=> [TONY] WEEK 01 solutions

contains-duplicate/jdalma.kt, kth-smallest-element-in-a-bst/jdalma.kt, number-of-1-bits/jdalma.kt, palindromic-substrings/jdalma.kt, top-k-frequent-elements/jdalma.kt
=> [정현준] 1주차 답안 제출

contains-duplicate/EGON.py, contains-duplicate/EGON.swift, kth-smallest-element-in-a-bst/EGON.py, kth-smallest-element-in-a-bst/EGON.swift, number-of-1-bits/EGON.py, number-of-1-bits/EGON.swift, palindromic-substrings/EGON.py, palindromic-substrings/EGON.swift, top-k-frequent-elements/EGON.py, top-k-frequent-elements/EGON.swift
=> [EGON] Week 01 Solutions

contains-duplicate/wooseok123.js, kth-smallest-element-in-a-bst/wooseok123.js, number-of-1-bits/wooseok123.js, palindromic-substrings/wooseok123.js, top-k-frequent-elements/wooseok123.js
=> [솔방울] week 1 문제 풀이

contains-duplicate/wogha95.js, kth-smallest-element-in-a-bst/wogha95.js, number-of-1-bits/wogha95.js, palindromic-substrings/wogha95.js, top-k-frequent-elements/wogha95.js
- 시간 복잡도가 O(n^2) 인 로직 이해중입니다.!
=> [재호] WEEK 01 solutions

contains-duplicate/HC-kang.ts, kth-smallest-element-in-a-bst/HC-kang.ts, number-of-1-bits/HC-kang.ts, palindromic-substrings/HC-kang.ts, top-k-frequent-elements/HC-kang.ts
=> [강희찬] Week1 문제 풀이

contains-duplicate/tolluset.ts, kth-smallest-element-in-a-bst/tolluset.ts, number-of-1-bits/tolluset.ts, palindromic-substrings/tolluset.ts, top-k-frequent-elements/tolluset.ts
=> [이병현] Week 1

contains-duplicate/kimyoung.js, kth-smallest-element-in-a-bst/kimyoung.js, number-of-1-bits/kimyoung.js, palindromic-substrings/kimyoung.js, top-k-frequent-elements/kimyoung.js
=> [kimyoung] WEEK 01 Solutions

contains-duplicate/yeongu.cpp, kth-smallest-element-in-a-bst/yeongu.cpp, number-of-1-bits/yeongu.cpp, palindromic-substrings/yeongu.cpp, top-k-frequent-elements/yeongu.cpp
=> [영우] Week 1 풀이 제출

contains-duplicate/naringst.js, number-of-1-bits/naringst.js, palindromic-substrings/naringst.js, top-k-frequent-elements/naringst.js
=> [나리] WEEK 01 Solutions

contains-duplicate/dm.py, number-of-1-bits/dm.py, palindromic-substrings/dm.py, top-k-frequent-elements/dm.py
안녕하세요, 문제 풀이 내용을 간단하게 정리해보았습니다.
많은 피드백 부탁 드립니다.. 🙇‍♀️ 
문제 #252 번은 좀 더 고민해보고 싶어서 백로그로 남겨두고, 다음 PR에 같이 올려보겠습니다..!
주어진 배열을 Set으로 변환한 후, 배열의 길이와 Set의 길이를 비교하여 중복되는 요소가 있는지를 판단하였습니다.
주어진 배열의 길이를 n이라 할때, 
- 시간 복잡도: O(n), 배열의 각 요소를 Set에 추가할 때 중복을 확인하고, 요소를 추가하는 데 모든 요소에 대해서 한번씩 처리해야 합니다.
- 공간 복잡도: O(n), 최악의 경우(모든 요소가 고유할 때), Set에는 n개의 요소가 저장됩니다.
주어진 정수(`n`)의 각 비트를 확인하여 1인 비트의 개수를 재귀적으로 세는 함수를 작성하였습니다.
1의 개수는 `acc`라는 변수에 누적한 뒤, 최종적으로 반환합니다.
주어진 정수를 n이라 할 때,
- 시간 복잡도: O(logn), 입력으로 받은 정수 `n`을 2로 나뉘면서 재귀적으로 호출하므로, 매 호출마다 `n`의 크기는 절반으로 줄어듭니다.
- 공간 복잡도: O(logn), 공간 복잡도는 재귀 호출의 깊이에 따라 결정됩니다. 최대 재귀 깊이는 log(n)이므로, 공간 복잡도는 O(logn)입니다.
각 요소의 빈도를 계산하고, 이 빈도를 인덱스로 사용하는 일종의 버킷을 만들어 문제를 해결했습니다.
가장 많이 등장하는 k를 추출해야 하기 때문에 빈도가 높은 순서대로 버킷을 조회하여 효율성을 높였습니다.
주어진 숫자 배열(`nums`)의 길이를 n이라 할 때,
- 시간 복잡도: O(n), 각 요소의 빈도 …
=> [DM] Week 01 Solutions

contains-duplicate/seona926.js, number-of-1-bits/seona926.js
1. contains duplicate
시간/공간 복잡도: O(n)
2. number-of-1-bits
* 시간복잡도: O(logN)
* 공간복잡도: O(1)
* 접근방법: 처음에는 sum과 i라는 변수를 두고, 2진수의 가장 우측부터 인덱스 0으로 보고 sum에 2의 i제곱을 더해보며 n과 비교하는 방식으로 접근하였으나 문제 해결에 시간이 많이 소요되어 다른 풀이를 참고하였습니다. sum을 2로 나누면서 2진수의 비트를 하나씩 확인하는 방식이 새로웠습니다.
+ 금주는 목~일 개인적인 사정으로 두 문제 밖에 풀지 못할 것 같습니다.. 다음주부터 더 화이팅 하겠습니다.
=> [sophia] Week1 문제풀이

contains-duplicate/whewchews.ts, kth-smallest-element-in-a-bst/whewchews.ts, number-of-1-bits/whewchews.ts, palindromic-substrings/whewchews.ts, top-k-frequent-elements/whewchews.ts
=> [pepper] Week 1 Solutions

construct-binary-tree-from-preorder-and-inorder-traversal/jdalma.kt, counting-bits/jdalma.kt, decode-ways/jdalma.kt, encode-and-decode-strings/jdalma.kt, valid-anagram/jdalma.kt
=> [정현준] 2주차 답안 제출

construct-binary-tree-from-preorder-and-inorder-traversal/whewchews.ts, counting-bits/whewchews.ts, decode-ways/whewchews.ts, valid-anagram/whewchews.ts
=> [pepper] WEEK 2 Solution

construct-binary-tree-from-preorder-and-inorder-traversal/TomyKim9401.java, counting-bits/TonyKim9401.java, decode-ways/TonyKim9401.java, encode-and-decode-strings/TonyKim9401.java, valid-anagram/TonyKim9401.java
=> [TONY] WEEK 02 Solutions

construct-binary-tree-from-preorder-and-inorder-traversal/kayden.py, counting-bits/kayden.py, decode-ways/kayden.py, encode-and-decode-strings/kayden.py, valid-anagram/kayden.py
=> [kayden] Week 02 Solutions 

construct-binary-tree-from-preorder-and-inorder-traversal/taekwon-dev.java, counting-bits/taekwon-dev.java, valid-anagram/taekwon-dev.java
=> [윤태권] Week2 문제 풀이

construct-binary-tree-from-preorder-and-inorder-traversal/highball.js, counting-bits/highball.js, encode-and-decode-strings/highball.js, valid-anagram/highball.js
=> [highball] week2 solutions

construct-binary-tree-from-preorder-and-inorder-traversal/sunjae95.js, counting-bits/sunjae95.js, decode-ways/sunjae95.js, palindromic-substrings/sunjae95.js, valid-anagram/sunjae95.js
@DaleSeo @YeonguChoe 두분 피드백 내용 적용했습니다.
@DaleSeo님 피드백 받을 때 제 컴퓨터환경이 끊기면서 듣게돼서 달레님 의도와 다르게 적용했을수도 있을거 같아 코멘트 남깁니다.
두분의 리뷰를 코드에 적용해보니 결국 https://www.algodale.com/problems/palindromic-substrings/ 의 3번째 솔루션으로 가는걸 발견했습니다.
피드백 감사합니다 :)
=> [선재] WEEK02 Solutions

construct-binary-tree-from-preorder-and-inorder-traversal/seona926.js, contains-duplicate/seona926.js, counting-bits/seona926.js, decode-ways/seona926.js, number-of-1-bits/seona926.js, valid-anagram/seona926.js
1. construct-binary-tree-from-preorder-and-inorder-traversal과 decode-ways 문제는 tree 문제가 익숙치 않아 다른 풀이를 참고하였습니다.
2. 오늘 다른 author 계정으로 설정된채로 커밋이 올라가서 원래 계정으로 수정하는 과정에서 이전에 커밋한 부분까지 날짜가 오늘로 변경되어버렸습니다..!😭
=> [sophia] Week2 답안 제출

construct-binary-tree-from-preorder-and-inorder-traversal/f-exuan21.java, counting-bits/f-exuan21.java, valid-anagram/f-euxan21.java
=> [아현] WEEK02 Solutions

construct-binary-tree-from-preorder-and-inorder-traversal/heozeop.cpp, counting-bits/heozeop.cpp, decode-ways/heozeop.cpp, encode-and-decode-strings/heozeop.cpp, valid-anagram/heozeop.cpp
=> [crispy] week 2 solution

construct-binary-tree-from-preorder-and-inorder-traversal/mangodm-web.py, counting-bits/mangodm-web.py, decode-ways/mangodm-web.py, encode-and-decode-strings/mangodm-web.py, valid-anagram/mangodm-web.py
=> [mangodm-web] Week 02 Solutions

construct-binary-tree-from-preorder-and-inorder-traversal/tolluset.ts, counting-bits/tolluset.ts, decode-ways/tolluset.ts, encode-and-decode-strings/tolluset.ts, valid-anagram/tolluset.ts
=> [이병현] Week 2

counting-bits/kimyoung.js, encode-and-decode-strings/kimyoung.js, valid-anagram/kimyoung.js
=> [kimyoung] WEEK 02 Solutions

.github/labeler.yml, .github/workflows/automation.yaml
- Fixes: #368
- 2024-08-25(일) 정기 스터디 모임 이후 운영진들과 나눈 대화에서 labeler 를 `pull_request_target` 이벤트를 사용하여 해결해보기로 결정.
- 자체 테스트를 해보니 직접 구현하는 방법도 좋지만, @DaleSeo 님, @sounmind 님이 이 알려주신 GitHub Actions 의 `actions/labeler` 를 사용하는 게 더 깔끔한 구현이 가능하여 이를 사용하여 작업 진행. 
- @sounmind 의 [예제 작업](https://github.com/DaleStudy/leetcode-study/pull/372) 잘 참고하였습니다. 감사합니다 에반님! 그리고 가이드 주셔서 감사합니다 달레님! 🙇
- [actions/labeler](https://github.com/actions/labeler) 의 사용법대로, `.github/labeler.yml` 에 원하는 조건과 label 구성을 정의
- `pull_request_target` 이벤트 기반으로 작성하던 기존 `automation` 이벤트에 `label-lang` job 새로 추가
- [지난 번](https://github.com/DaleStudy/leetcode-study/pull/335)과 달리 이번에는 `fork` repository 에서 base repository 로 PR 을 열어 테스트를 진행함. 
- 테스트 수행 결과 -> 정상 작동 확인 
> [!NOTE]
> `pull_request_target` 는 `pull_request` 와 달리, base repo의 컨텍스트를 기반으로 …
=> ci: add pr langauge labeler on `pull_request_target` event

climbing-stairs/HC-kang.ts, coin-change/HC-kang.ts, combination-sum/HC-kang.ts, product-of-array-except-self/HC-kang.ts, two-sum/HC-kang.ts
=> [강희찬] WEEK 3 Solution

climbing-stairs/tolluset.ts, coin-change/tolluset.ts, combination-sum/tolluset.ts, product-of-array-except-self/tolluset.ts, two-sum/tolluset.ts
=> [이병현] Week 3

climbing-stairs/bemelon.py, coin-change/bemelon.py, combination-sum/bemelon.py, product-of-array-except-self/bemelon.py, two-sum/bemelon.py
=> [BEMELON] WEEK 3 Solution

climbing-stairs/heozeop.cpp, coin-change/heozeop.cpp, combination-sum/heozeop.cpp, product-of-array-except-self/heozeop.cpp, two-sum/heozeop.cpp
=> [crispy] 3 week solution

climbing-stairs/jdalma.kt, coin-change/jdalma.kt, combination-sum/jdalma.kt, product-of-array-except-self/jdalma.kt, two-sum/jdalma.kt
=> [정현준] 3주차 답안 추가

climbing-stairs/taekwon-dev.java, combination-sum/taekwon-dev.java, two-sum/taekwon-dev.java
=> [윤태권] Week3 문제 풀이

climbing-stairs/naringst.js, coin-change/naringst.js, combination-sum/naringst.js, product-of-array-except-self/naringst.js, two-sum/naringst.js
=> [나리] WEEK 03 Solutions

climbing-stairs/TonyKim9401.java, coin-change/TonyKim9401.java, combination-sum/TonyKim9401.java, product-of-array-except-self/TonyKim9401.java, two-sum/TonyKim9401.java
=> [TONY] WEEK 03 Solutions

climbing-stairs/gitsunmin.ts, product-of-array-except-self/gitsunmin.ts, two-sum/gitsunmin.ts
=> [gitsunmin] Week3 Solutions

climbing-stairs/hyejjun.js, two-sum/hyejjun.js
=> [이혜준] Week3 문제 풀이

two-sum/GUMUNYEONG.js
=> [GUMUNYEONG] Week3 문제풀이

climbing-stairs/kayden.py, combination-sum/kayden.py, encode-and-decode-strings/kayden.py, product-of-array-except-self/kayden.py, two-sum/kayden.py
=> [kayden] Week 03 Solutions 

climbing-stairs/seona926.js, two-sum/seona926.js
=> [Sophia] Week3 Solutions

climbing-stairs/mangodm-web.py, product-of-array-except-self/mangodm-web.py, two-sum/mangodm-web.py
안녕하세요,
이번 주에는 세 문제를 풀어봤습니다.
리뷰해주셔서 감사합니다. 😄
- #219 
- #239 
- #230 
배열의 모든 요소를 순회하면서 순회중인 요소와 더해서 목표로 하는 값(`target`)이 딕셔너리(`index_map`)에 있는지 확인합니다.
요소가 있다면, 두 수의 인덱스를 배열에 넣어서 반환합니다.
없다면, 해당 요소를 키로, 요소의 인덱스를 값으로 `index_map`에 추가합니다.
O(n), 최악의 경우 배열의 모든 요소를 순회해야 하기 때문에 O(n)로 판단했어요.
O(n), 배열의 크기만큼의 요소를 `index_map`에 저장하기 때문에 O(n)로 판단했어요.
계단 i번째에 도달하는 방법의 수는 i-1번째 계단에서 한 계단 올라오는 방법과 i-2번째 계단에서 두 계단 올라오는 방법을 합한다는 개념을 이용해서 문제를 풀었습니다!
O(n), n개의 계단에 대해 각 경우의 수를 계산하기 위해 반복문이 n번 실행되기 때문에 O(n)으로 판단했어요.
O(n), n개의 계단까지 도달하는 방법의 수를 배열에 저장하기 때문에 O(n)으로 판단했어요.
i번째 요소를 제외한 나머지 수들의 곱은 i-1번째까지 요소들의 곱과 i+1번째부터 마지막 요소까지의 곱으로 구할 수 있다는 개념을 이용했습니다.
O(n), 왼쪽/오른쪽 요소들의 곱으로 이뤄진 배열을 만들어내는 데 배열의 크기 만큼 연산이 필요하기 때문에 O(n)으로 판단했어요.
O(n), 왼쪽/오른쪽 요소들의 곱으로 이뤄진 배열을 만들어내는 데 배열의 크기 만큼의 공간이 필요하기 때문에 O(n)으로 판단했어요.
=> [mangodm-web] Week 03 Solutions 

longest-consecutive-sequence/tolluset.ts, maximum-subarray/tolluset.ts, missing-number/tolluset.ts, valid-palindrome/tolluset.ts, word-search/tolluset.ts
=> [이병현] Week 4

longest-consecutive-sequence/TonyKim9401.java, maximum-product-subarray/TonyKim9401.java, missing-number/TonyKim9401.java, valid-palindrome/TonyKim9401.java, word-search/TonyKim9401.java
=> [TONY] WEEK 04 Solutions

longest-consecutive-sequence/jdalma.kt, maximum-product-subarray/jdalma.kt, missing-number/jdalma.kt, valid-palindrome/jdalma.kt, word-search/jdalma.kt
=> [정현준] 4주차 답안 제출

missing-number/hyejjun.js, valid-palindrome/hyejjun.js
=> [혜준] Week4 문제풀이

longest-consecutive-sequence/highball.js, maximum-product-subarray/highball.js, missing-number/highball.js, valid-palindrome/highball.js, word-search/highball.js
=> [highball] week4 solutions

longest-common-subsequence/kayden.py, maximum-product-subarray/kayden.py, missing-number/kayden.py, valid-palindrome/kayden.py, word-search/kayden.py
=> [kayden] Week 04 Solutions

missing-number/GUMUNYEONG.js, valid-palindrome/GUMUNYEONG.js
=> [GUMUNYEONG] Week4 Solutions

longest-consecutive-sequence/sunjae95.js, maximum-product-subarray/sunjae95.js, missing-number/sunjae95.js, valid-palindrome/sunjae95.js, word-search/sunjae95.js
=> [선재] WEEK4 Solution

longest-consecutive-sequence/flynn.cpp, maximum-product-subarray/flynn.cpp, missing-number/flynn.cpp, valid-palindrome/flynn.cpp, word-search/flynn.cpp
=> [Flynn] week4

longest-consecutive-sequence/wogha95.js, maximum-product-subarray/wogha95.js, missing-number/wogha95.js, valid-palindrome/wogha95.js, word-search/wogha95.js
=> [재호] WEEK 04 Solutions

longest-consecutive-sequence/heozeop.cpp, missing-number/heozeop.cpp, valid-palindrome/heozeop.cpp, word-search/heozeop.cpp
> - [x] https://github.com/DaleStudy/leetcode-study/issues/270
- 풀이 보고 했는데 이해가 안가서... 안푼 걸로 하고 나중에 다시 풀려고 합니다...
=> [crispy] week 4 solution

missing-number/taekwon-dev.java, valid-palindrome/taekwon-dev.java
=> [윤태권] Week4 문제 풀이

longest-consecutive-sequence/hwanmini.js, missing-number/hwanmini.js, valid-palindrome/hwanmini.js, word-search/hwanmini.js
=> [환미니니] Week4 문제풀이

missing-number/naringst.js, valid-palindrome/naringst.js
=> [나리] WEEK04 Solutions 

valid-palindrome/seona926.js
=> [Sophia] Week4 Solution

longest-consecutive-sequence/EGON.py, maximum-subarray/EGON.py, missing-number/EGON.py, valid-palindrome/EGON.py, word-search/EGON.py
=> [EGON] Week 4 Solutions

best-time-to-buy-and-sell-stock/hyejjun.js, group-anagrams/hyejjun.js
=> [혜준] Week5 문제 풀이

3sum/taekwon-dev.java, best-time-to-buy-and-sell-stock/taekwon-dev.java, group-anagrams/taekwon-dev.java
=> [윤태권] Week5 문제 풀이

3sum/flynn.py, best-time-to-buy-and-sell-stock/flynn.py, group-anagrams/flynn.py, implement-trie-prefix-tree/flynn.py, word-break/flynn.py
=> [Flynn] Week 5

3sum/tolluset.ts, best-time-to-buy-and-sell-stock/tolluset.ts, group-anagrams/tolluset.ts, implement-trie-prefix-tree/tolluset.ts, word-break/tolluset.ts
=> [이병현] Week 5

best-time-to-buy-and-sell-stock/kimyoung.js
=> [kimyoung] WEEK 05 Solutions

best-time-to-buy-and-sell-stock/GUMUNYEONG.js
- [] 코드 검토자 1분 이상으로부터 승인을 받으셨다면 PR을 병합해주세요.
=> [GUMUNYEONG] week 5 solution

3sum/wogha95.js, best-time-to-buy-and-sell-stock/wogha95.js, group-anagrams/wogha95.js, implement-trie-prefix-tree/wogha95.js, word-break/wogha95.js
=> [재호] WEEK 05 Solutions

best-time-to-buy-and-sell-stock/sunjae95.js, group-anagrams/sunjae95.js
=> [선재] WEEK05 문제 풀이

container-with-most-water/EGON.py, design-add-and-search-words-data-structure/EGON.py, longest-increasing-subsequence/EGON.py, spiral-matrix/EGON.py, valid-parentheses/EGON.py
=> [EGON] Week 6 Solutions

container-with-most-water/HC-kang.ts, design-add-and-search-words-data-structure/HC-kang.ts, longest-increasing-subsequence/HC-kang.ts, spiral-matrix/HC-kang.ts, valid-parentheses/HC-kang.ts
=> [강희찬] WEEK 6 Solution

spiral-matrix/flynn.cpp
기존 PR 병합 후에 다른 방법이 생각나서 새로운 PR을 열게 되었습니다 😓😓
=> [Flynn] Week 6 Sprial Matrix Refactor

container-with-most-water/wogha95.js, design-add-and-search-words-data-structure/wogha95.js, longest-increasing-subsequence/wogha95.js, spiral-matrix/wogha95.js, valid-parentheses/wogha95.js
=> [재호] WEEK 06 Solutions

container-with-most-water/sunjae95.js, longest-increasing-subsequence/sunjae95.js, spiral-matrix/sunjae95.js, valid-parentheses/sunjae95.js
=> [선재] WEEK06 문제 풀이

container-with-most-water/jaejeong1.java, design-add-and-search-words-data-structure/jaejeong1.java, valid-parentheses/jaejeong1.java
=> [jaejeong1] Week 6

container-with-most-water/TonyKim9401.java, design-add-and-search-words-data-structure/TonyKim9401.java, longest-increasing-subsequence/TonyKim9401.java, spiral-matrix/TonyKim9401.java, valid-parentheses/TonyKim9401.java
=> [TONY] WEEK 06 Solutions

container-with-most-water/hwanmini.js, design-add-and-search-words-data-structure/hwanmini.js, spiral-matrix/hwanmini.js, valid-parentheses/hwanmini.js
=> [환미니니] Week6 문제풀이

container-with-most-water/taekwon-dev.java, design-add-and-search-words-data-structure/taekwon-dev.java, valid-parentheses/taekwon-dev.java
=> [윤태권] Week6 문제 풀이

container-with-most-water/mangodm-web.py, spiral-matrix/mangodm-web.py, valid-parentheses/mangodm-web.py
=> [mangodm-web] Week 06 Solutions

container-with-most-water/whewchews.ts, design-add-and-search-words-data-structure/whewchews.ts, spiral-matrix/whewchews.ts, valid-parentheses/whewchews.ts
=> [pepper] Week 6 Solutions 

longest-substring-without-repeating-characters/yeonguchoe.cpp, number-of-islands/yeonguchoe.cpp, reverse-linked-list/yeonguchoe.c, set-matrix-zeroes/yeonguchoe.c, unique-paths/yeonguchoe.cpp
=> [영우] Week7 Solutions

longest-substring-without-repeating-characters/EGON.py, number-of-islands/EGON.py, reverse-linked-list/EGON.py, set-matrix-zeroes/EGON.py, unique-paths/EGON.py
=> [EGON] Week7 Solutions

longest-substring-without-repeating-characters/TonyKim9401.java, number-of-islands/TonyKim9401.java, reverse-linked-list/TonyKim9401.java, set-matrix-zeroes/TonyKim9401.java, unique-paths/TonyKim9401.java
=> [TONY] WEEK 07 Solutions

longest-substring-without-repeating-characters/sunjae95.js, number-of-islands/sunjae95.js, reverse-linked-list/sunjae95.js, set-matrix-zeroes/sunjae95.js, unique-paths/sunjae95.js
=> [선재] WEEK07 문제풀이

longest-substring-without-repeating-characters/HC-kang.ts, number-of-islands/HC-kang.ts, reverse-linked-list/HC-kang.ts, set-matrix-zeroes/HC-kang.ts, unique-paths/HC-kang.ts
=> [강희찬] WEEK 7 Solution

longest-substring-without-repeating-characters/jaejeong1.java, number-of-islands/jaejeong1.java, reverse-linked-list/jaejeong1.java
=> [jaejeong1] WEEK 07 Solutions

longest-substring-without-repeating-characters/hwanmini.js, number-of-islands/hwanmini.js, reverse-linked-list/hwanmini.js, set-matrix-zeroes/hwamini.js
=> [환미니니] Week7 문제풀이

.github/labeler.yml, .github/workflows/integration.yaml
- 빈 파일에 대한 line lint 체크를 무시하도록 수정했습니다.
- GitHub 에서도 개행 체크를 하지 않으니 통합 워크플로에서도 검사를 수행하지 않기로 @DaleSeo 님과 이야기를 나누었습니다.
- `C` 및 `C#` 파일에 대한 라벨 설정을 추가했습니다.
-  아직 소수의 인원이 사용하지만, 알고리즘에 c 계열 언어를 지원하는 경우가 굉장히 많고, 이곳 Repository 가 다양한 언어를 수용하는 곳이기 때문에 추가해두었습니다.
> 아래 테스트는 제 개인 Repo 에서 진행하였습니다.
- 빈 파일에 대한 line lint 체크를 무시하도록 수정했습니다.
- **변경 전: 워크플로 실패 및 Summary 존재**
- PR 하단
- GitHub Actions Summary 
- **변경 후: 워크플로 성공 및 Summary 없음**
- `C` 및 `C#` 파일에 대한 라벨 설정을 추가했습니다.
=> ci: ignore line lint for empty files, add C/C# labels

clone-graph/EGON.py, longest-common-subsequence/EGON.py, longest-repeating-character-replacement/EGON.py, merge-two-sorted-lists/EGON.py, sum-of-two-integers/EGON.py
=> [EGON] Week8 Solutions

clone-graph/TonyKim9401.java, longest-common-subsequence/TonyKim9401.java, longest-repeating-character-replacement/TonyKim9401.java, merge-two-sorted-lists/TonyKim9401.java, sum-of-two-integers/TonyKim9401.java
=> [TONY] Week 08 Solutions

clone-graph/jdalma.kt, longest-common-subsequence/jdalma.kt, longest-repeating-character-replacement/jdalma.kt, merge-two-sorted-lists/jdalma.kt
=> [정현준] 8주차 제출

clone-graph/jaejeong1.java, longest-repeating-character-replacement/jaejeong1.java, merge-two-sorted-lists/jaejeong1.java
=> [jaejeong1] Week 08 Solutions

clone-graph/kayden.py, longest-common-subsequence/kayden.py, longest-consecutive-sequence/kayden.py, longest-repeating-character-replacement/kayden.py, merge-two-sorted-lists/kayden.py, sum-of-two-integers/kayden.java
Longest Consecutive Sequence 파일 위치가 잘못되어 있어서 수정 하였습니다!
=> [kayden] Week 08 Solutions 

longest-repeating-character-replacement/mangodm-web.py, merge-two-sorted-lists/mangodm-web.py
=> [mangodm-web] Week 08 Solutions

find-minimum-in-rotated-sorted-array/flynn.go, linked-list-cycle/flynn.go, maximum-subarray/flynn.go, minimum-window-substring/flynn.go, pacific-atlantic-water-flow/flynn.go
=> [Flynn] Week 09

find-minimum-in-rotated-sorted-array/TonyKim9401.java, linked-list-cycle/TonyKim9401.java, maximum-subarray/TonyKim9401.java, minimum-window-substring/TonyKim9401.java, pacific-atlantic-water-flow/TonyKim9401.java
=> [Tony] WEEK 09 Solutions

find-minimum-in-rotated-sorted-array/mangodm-web.py, linked-list-cycle/mangodm-web.py
=> [mangodm-web] Week 09 Solutions

find-minimum-in-rotated-sorted-array/kayden.py, linked-list-cycle/kayden.py, maximum-subarray/kayden.py, minimum-window-substring/kayden.py, pacific-atlantic-water-flow/kayden.py
너무 늦게 올렸네요.. 면접이 많이 잡혀서 급하게 풀고 올립니다!
=> [kayden] Week 09 Solutions 

find-minimum-in-rotated-sorted-array/EGON.py, linked-list-cycle/EGON.py, maximum-product-subarray/EGON.py, maximum-subarray/EGON.py, minimum-window-substring/EGON.py, pacific-atlantic-water-flow/EGON.py
=> [EGON]] Week9 Solutions

find-minimum-in-rotated-sorted-array/gitsunmin.ts, linked-list-cycle/gitsunmin.ts, pacific-atlantic-water-flow/gitsunmin.ts
=> [gitsunmin] Week 09 Solutions

find-minimum-in-rotated-sorted-array/HC-kang.ts, linked-list-cycle/HC-kang.ts, maximum-subarray/HC-kang.ts, minimum-window-substring/HC-kang.ts, pacific-atlantic-water-flow/HC-kang.ts
=> [강희찬] WEEK 9 Solution

find-minimum-in-rotated-sorted-array/jaejeong1.java, linked-list-cycle/jaejeong1.java
=> [jaejeong1] WEEK 09 Solutions

course-schedule/flynn.go, invert-binary-tree/flynn.go, jump-game/flynn.go, merge-k-sorted-lists/flynn.go, search-in-rotated-sorted-array/flynn.go
=> [Flynn] Week 10

course-schedule/HC-kang.ts, invert-binary-tree/HC-kang.ts, jump-game/HC-kang.ts, merge-k-sorted-lists/HC-kang.ts, search-in-rotated-sorted-array/HC-kang.ts
=> [강희찬] WEEK 10 Solution

course-schedule/TonyKim9401.java, invert-binary-tree/TonyKim9401.java, jump-game/TonyKim9401.java, merge-k-sorted-lists/TonyKim9401.java, search-in-rotated-sorted-array/TonyKim9401.java
=> [Tony] WEEK 10 Solutions

course-schedule/sunjae95.js, invert-binary-tree/sunjae95.js, jump-game/sunjae95.js, merge-k-sorted-lists/sunjae95.js, search-in-rotated-sorted-array/sunjae95.js
=> [선재] WEEK10 Solutions

course-schedule/jdalma.kt, invert-binary-tree/jdalma.kt, jump-game/jdalma.kt, merge-k-sorted-lists/jdalma.kt, search-in-rotated-sorted-array/jdalma.kt
=> [정현준] 10주차

course-schedule/kayden.py, invert-binary-tree/kayden.py, jump-game/kayden.py, merge-k-sorted-lists/kayden.py, search-in-rotated-sorted-array/kayden.py
=> [kayden] Week 10 Solutions 

binary-tree-maximum-path-sum/flynn.go, graph-valid-tree/flynn.go, insert-interval/flynn.go, maximum-depth-of-binary-tree/flynn.go, reorder-list/flynn.go
=> [Flynn] week 11

binary-tree-maximum-path-sum/TonyKim9401.java, graph-valid-tree/TonyKim9401.java, insert-interval/TonyKim9401.java, maximum-depth-of-binary-tree/TonyKim9401.java, reorder-list/TonyKim9401.java
=> [Tony] WEEK 11 Solutions

binary-tree-maximum-path-sum/jdalma.kt, graph-valid-tree/jdalma.kt, insert-interval/jdalma.kt, maximum-depth-of-binary-tree/jdalma.kt, reorder-list/jdalma.kt
=> [정현준] 11주차

graph-valid-tree/hwanmini.js, maximum-depth-of-binary-tree/hwanmini.js
=> [환미니니] Week11 Solutions

graph-valid-tree/mangodm-web.py, maximum-depth-of-binary-tree/mangodm-web.py, reorder-list/mangodm-web.py
=> [mangodm-web] Week11 Solutions

binary-tree-maximum-path-sum/EGON.py, graph-valid-tree/EGON.py, insert-interval/EGON.py, maximum-depth-of-binary-tree/EGON.py, reorder-list/EGON.py
=> [EGON] Week11 Solutions

merge-intervals/EGON.py, number-of-connected-components-in-an-undirected-graph/EGON.py, remove-nth-node-from-end-of-list/EGON.py, same-tree/EGON.py, serialize-and-deserialize-binary-tree/EGON.py
=> [EGON] Week12 Solutions

merge-intervals/flynn.go, number-of-connected-components-in-an-undirected-graph/flynn.go, remove-nth-node-from-end-of-list/flynn.go, same-tree/flynn.go, serialize-and-deserialize-binary-tree/flynn.go
=> [Flynn] Week 12

merge-intervals/jaejeong1.java, remove-nth-node-from-end-of-list/jaejeong1.java, same-tree/jaejeong1.java
=> [jaejeong1] WEEK 12 Solutions

maximum-subarray/jdalma.kt, number-of-connected-components-in-an-undirected-graph/jdalma.kt, remove-nth-node-from-end-of-list/jdalma.kt, same-tree/jdalma.kt, serialize-and-deserialize-binary-tree/jdalma.kt
=> [정현준] 12주차

merge-intervals/haklee.py, number-of-connected-components-in-an-undirected-graph/haklee.py, remove-nth-node-from-end-of-list/haklee.py, same-tree/haklee.py, serialize-and-deserialize-binary-tree/haklee.py
=> [haklee] week 12

merge-intervals/HC-kang.ts, number-of-connected-components-in-an-undirected-graph/HC-kang.ts, remove-nth-node-from-end-of-list/HC-kang.ts, same-tree/HC-kang.ts, serialize-and-deserialize-binary-tree/HC-kang.ts
=> [강희찬] WEEK 12 Solution

remove-nth-node-from-end-of-list/mangodm-web.py, same-tree/mangodm-web.py
=> [mangodm-web] Week12 Solutions

merge-intervals/sunjae95.js, remove-nth-node-from-end-of-list/sunjae.js, same-tree/sunjae95.js
=> [선재] WEEK 12 Solution 

merge-intervals/gitsunmin.ts, remove-nth-node-from-end-of-list/gitsunmin.ts, same-tree/gitsunmin.ts
=> [gitsunmin] Week12 Solutions

house-robber/jdalma.kt, lowest-common-ancestor-of-a-binary-search-tree/jdalma.kt, meeting-rooms/MeetingRooms.java, meeting-rooms/jdalma.java
=> [정현준] 13주차

.github/workflows/automation.yaml, .gitignore
- GitHub CLI 를 사용하여 PR 리뷰어를 자동 할당하는 automation job 을 추가합니다.
- 리뷰어 조회 조건
  - ~Closed PR 은 제외함 (실수로 올렸다 닫는 경우가 종종 있으므로) -> opened, merged PR 만 조회~ (하단 코멘트 참고)
  - 찾은 PR 중 현재 PR에 가장 근접한 PR의 작성자여야 함 (created 로 역순 정렬)
  - 현재 PR과 다른 이름의 작성자여야 함
  - 현재 PR 보다 이전에 생성된 PR의 작성자여야 함
```
previous_pr_author=$(gh pr list --repo $current_repo \
--search "-is:closed sort:created-desc -author:$current_pr_author" \
--limit 3 --json number,author \
--jq 'map(select(.number < '$current_pr_num'))[0].author.login')
```            
- 그외 .gitignore 업데이트
- 현재 PR처럼 문제풀이와 상관없는 PR이 올라올 경우에도, 마지막 PR 작성자를 리뷰어로 할당받게 됨. (지금은 merge가 안됐기 때문에 적용되진 않지만) 
- 새로운 기수가 처음 등록하는 PR 에서는 직전 기수의 마지막 PR 작성자를 리뷰어로 할당받게 됨.
> 위 두 문제는 식별가능한 label 을 미리 설정하는 것으로 해결할 수 있을 것 같지만 그렇게 하기엔 손이 많이 가서 우선 보류합니다..
=> ci: add assign-reviewer job

house-robber/jaejeong1.java, lowest-common-ancestor-of-a-binary-search-tree/jaejeong1.java, meeting-rooms/jaejeong1.java, non-overlapping-intervals/jaejeong1.java
=> [jaejeong1] Week 13 Solutions

house-robber/gitsunmin.ts, lowest-common-ancestor-of-a-binary-search-tree/gitsunmin.ts, meeting-rooms/gitsunmin.ts
=> [gitsunmin] Week 13 Solutions

house-robber/sunjae95.js, lowest-common-ancestor-of-a-binary-search-tree/sunjae95.js, non-overlapping-intervals/sunjae95.js
=> [선재] Week13

find-median-from-data-stream/HC-kang.ts, house-robber/HC-kang.ts, lowest-common-ancestor-of-a-binary-search-tree/HC-kang.ts, meeting-rooms/HC-kang.ts, non-overlapping-intervals/HC-kang.ts
=> [강희찬] WEEK 13 Solution

find-median-from-data-stream/EGON.py, house-robber/EGON.py, lowest-common-ancestor-of-a-binary-search-tree/EGON.py, meeting-rooms/EGON.py, non-overlapping-intervals/EGON.py
=> [EGON] Week13 Solutions

.github/workflows/automation.yaml
- [리소스 접근 제한 오류](https://github.com/DaleStudy/leetcode-study/actions/runs/11762079562/job/32764590050) 발생
- `error fetching organization teams: GraphQL: Resource not accessible by integration (organization.teams)`
- `gh pr edit --add-reviewer` 를 수행할 때, `organization teams` 를 읽는 과정이 포함되는데, 기본 제공하는 GitHub Actions Token 이 이 권한을 갖지 못하는 것으로 보임
- `organization teams` 를 획득하지 않고 `--add-reviewer` 동작을 수행하는 것 관련해서 이슈가 제기된 바 있음
- 이슈: https://github.com/cli/cli/issues/4844
- 관련하여 해결 [PR](https://github.com/cli/cli/pull/9037)이 열려있지만 아직 병합되지는 않았고, 작성 시기나 피드백 시기를 보았을 때 해결 우선순위가 높아보이지 않음 -> 현재 레포에서는 작업을 revert 하는 게 좋아 보임
- https://github.com/DaleStudy/leetcode-study/pull/529 작업을 revert 함
- 개인적으로 테스트하였을 때는 정상적으로 동작을 수행했는데, 권한 설정을 모두 차단(혹은 최소화)한 후 위 이슈 코멘트의 대안을 수행하거나, 다른 대안을 찾아볼 필요가 있음
=> Revert "ci: add assign-reviewer job (#529)"

binary-tree-level-order-traversal/jdalma.kt
=> [정현준] 14주차

binary-tree-level-order-traversal/TonyKim9401.java, house-robber-ii/TonyKim9401.java, meeting-rooms-ii/TonyKim9401.java, reverse-bits/TonyKim9401.java
=> [Tony] WEEK 14 Solutions

binary-tree-level-order-traversal/mangodm-web.py, house-robber-ii/mangodm-web.py
=> [mangodm-web] Week14 Solutions

binary-tree-level-order-traversal/flynn.go, house-robber-ii/flynn.go, meeting-rooms-ii/flynn.go, reverse-bits/flynn.go, word-search-ii/flynn.go
=> [Flynn] Week14

binary-tree-level-order-traversal/wogha95.js, house-robber-ii/wogha95.js, house-robber/wogha95.js, lowest-common-ancestor-of-a-binary-search-tree/wogha95.js, non-overlapping-intervals/wogha95.js, reverse-bits/wogha95.js
=> [재호] WEEK 14 Solutions

binary-tree-level-order-traversal/EGON.py, house-robber-ii/EGON.py, meeting-rooms-ii/EGON.py, reverse-bits/EGON.py, word-search-ii/EGON.py
=> [EGON] Week14 Solutions

binary-tree-level-order-traversal/sunjae95.js, house-robber-ii/sunjae95.js, reverse-bits/sunjae95.js
=> [선재] Week14

longest-palindromic-substring/TonyKim9401.java, rotate-image/TonyKim9401.java, subtree-of-another-tree/TonyKim9401.java, validate-binary-search-tree/TonyKim9401.java
=> [Tony] WEEK 15 Solutions

alien-dictionary/HC-kang.ts, longest-palindromic-substring/HC-kang.ts, rotate-image/HC-kang.ts, subtree-of-another-tree/HC-kang.ts, validate-binary-search-tree/HC-kang.ts
=> [강희찬] WEEK 15 Solution

alien-dictionary/EGON.py, longest-palindromic-substring/EGON.py, rotate-image/EGON.py, subtree-of-another-tree/EGON.py, validate-binary-search-tree/EGON.py
=> [EGON] Week15 Solutions

subtree-of-another-tree/jdalma.kt
=> [정현준] 15주차

longest-palindromic-substring/gitsunmin.ts, subtree-of-another-tree/gitsunmin.ts, validate-binary-search-tree/gitsunmin.ts
=> [gitsunmin] Week15 Solutions

subtree-of-another-tree/sunjae95.js
=> [선재] WEEK 15 Solutions

longest-palindromic-substring/wogha95.js, rotate-image/wogha95.js, subtree-of-another-tree/wogha95.js, validate-binary-search-tree/wogha95.js
=> [재호] WEEK 15 Solutions

longest-palindromic-substring/mangodm-web.py, subtree-of-another-tree/mangodm-web.py, validate-binary-search-tree/mangodm-web.py
=> [mangodm-web] Week15 Solutions

.github/workflows/automation.yaml, .github/workflows/integration.yaml, README.md
=> README.md에 3기 정보 추가

.github/workflows/integration.yaml
- 멤버분들께서 답안을 제출하실 때, 파일명을 "계정명.확장자" 형태로 강제하기 위한 CI 스텝을 추가합니다.
종종 아래와 같은 경우가 발생할 수 있습니다.
1. 답안 제출목적이 아닌, 워크플로우 수정이나 스크립트 추가 등의 작업이 필요한 경우
2. 필요에 따라 다른 사람의 답안을 수정해야 하는 경우
이러한 경우 `maintenance` 라벨을 사용하시면 해당 파일명 검증 스텝을 우회 할수 있습니다.
- 안내문구 자체는 파일명이 계정명과 일치하는 형태로 표현되고있으나, 사실 Prefix로 동작합니다.
- 대소문자는 구별하지 않습니다. (hc-kang, Hc-KaNg... 등 모두 허용)
=> Chore: integration workflow에 답안 파일 명을 "GitHub계정명".ext 형태로 강제하는 step 추가

contains-duplicate/jeldo.py, house-robber/jeldo.py, longest-consecutive-sequence/jeldo.py, top-k-frequent-elements/jeldo.py, valid-palindrome/jeldo.py
=> [jeldo3] Week1

contains-duplicate/JisooPyo.kt, house-robber/JisooPyo.kt, longest-consecutive-sequence/JisooPyo.kt, top-k-frequent-elements/JisooPyo.kt, valid-palindrome/JisooPyo.kt
=> [JisooPyo] Week 1

.github/workflows/integration.yaml
추가된 파일을 확인하기 위해 `diff` 할 때, 자신의 부모가 아니라 최신 브랜치와 비교하고 있었습니다.
이로인해 중간에 누군가 다른 멤버분께서 머지하시는 경우, 통합할 수 없는 상태가 되고있었네요.
=> fix(integration): Fix filename validation to compare with PR base SHA instead of latest branch

contains-duplicate/thispath98.py, house-robber/thispath98.py, longest-common-subsequence/thispath98.py, top-k-frequent-elements/thispath98.py, valid-palindrome/thispath98.py
=> [thispath98] Week 1

contains-duplicate/EcoFriendlyAppleSu.kt, house-robber/EcoFriendlyAppleSu.kt, longest-consecutive-sequence/EcoFriendlyAppleSu.kt, top-k-frequent-elements/EcoFriendlyAppleSu.kt, valid-palindrome/EcoFriendlyAppleSu.kt
=> [친환경사과] Week 1

contains-duplicate/neverlish.go, house-robber/neverlish.go, longest-consecutive-sequence/neverlish.go, top-k-frequent-elements/neverlish.go, valid-palindrome/neverlish.go
=> [jinho] Week 1

contains-duplicate/taewanseoul.ts, longest-consecutive-sequence/taewanseoul.ts, top-k-frequent-elements/taewanseoul.ts, valid-palindrome/taewanseoul.ts
=> [Wan] Week 1

contains-duplicate/mmyeon.js, house-robber/mmyeon.js, longest-common-subsequence/mmyeon.js, top-k-frequent-elements/mmyeon.js, valid-palindrome/mmyeon.js
=> [mallayon] Week 1

contains-duplicate/GangBean.java, house-robber/GangBean.java, longest-consecutive-sequence/GangBean.java, palindromic-substrings/GangBean.java, top-k-frequent-elements/GangBean.java, valid-palindrome/GangBean.java
=> [GangBean] Week 1

contains-duplicate/anniemon.js, longest-consecutive-sequence/anniemon.js, top-k-frequent-elements/anniemon.js, valid-palindrome/anniemon.js
=> [anniemon78] Week 1

contains-duplicate/jinah92.py, house-robber/jinah92.py, longest-consecutive-sequence/jinah92.py, top-k-frequent-elements/jinah92.py, valid-palindrome/jinah92.py
=> [jinah92] Week 1

contains-duplicate/HodaeSsi.py, house-robber/HodaeSsi.py, longest-consecutive-sequence/HodaeSsi.py, top-k-frequent-elements/HodaeSsi.py, valid-palindrome/HodaeSsi.py
=> [HodaeSsi] Week 1

.github/workflows/integration.yaml
- rebase 없이, 현재 PR과 upstream의 공통 조상을 찾아 filename을 비교토록 CI 워크플로우를 수정
- 수정/디버깅 편의성을 위한 디버그 메시지 추가
```diff
- files=$(git diff --name-only ${{ github.event.pull_request.base.sha }} ${{ github.event.pull_request.head.sha }} | tr -d '"')
+ # PR의 공통 조상 커밋을 찾아서 merge base로 설정
+ merge_base=$(git merge-base ${{ github.event.pull_request.base.sha }} ${{ github.event.pull_request.head.sha }})
+ files=$(git diff --name-only $merge_base ${{ github.event.pull_request.head.sha }} | tr -d '"')
```
위 변경사항은 [이 라인](https://github.com/DaleStudy/leetcode-study/compare/main...HC-kang:integration-hotfix?expand=1#diff-8eddb0045a2f69770230f0d41ff383cd2a7b040efe2881330606b787d97f48efR113)에서 확인하실 수 있습니다.
이전 수정에서
`github.sha`를 `github.event.pull_request.head.sha`로 수정했었는데, 이 부분이 github actions 상에서는 사실상 같은 위치를 바라보게 …
=> [CI integration] Rebase 없이 filename 체크가 성공할 수 있도록 개선

contains-duplicate/hanseulhee.js, house-robber/hanseulhee.js, longest-consecutive-sequence/hanseulhee.js, top-k-frequent-elements/hanseulhee.js, valid-palindrome/hanseulhee.js
=> [hanseulhyi] - Week 1

contains-duplicate/yoonthecoder.js, longest-consecutive-sequence/yoonthecoder.js, top-k-frequent-elements/yoonthecoder.js, valid-palindrome/yoonthecoder.js
=> [yoonthecoder] Week 1

contains-duplicate/ekgns33.java, valid-palindrome/ekgns33.java
=> [byteho0n] - Week 1

contains-duplicate/yolophg.py, longest-consecutive-sequence/yolophg.py, top-k-frequent-elements/yolophg.py, valid-palindrome/yolophg.py
=> [Helena] Week 1

contains-duplicate/suhacs.js, top-k-frequent-elements/suhacs.js, valid-palindrome/suhacs.js
=> [phenomenal_star_75309]

contains-duplicate/Totschka.ts, house-robber/Totschka.ts, longest-consecutive-sequence/Totschka.ts, top-k-frequent-elements/Totschka.ts, valid-palindrome/Totschka.ts
=> [TotschKa] Week 1

contains-duplicate/EstherKim97.py, top-k-frequent-elements/EstherKim97.py, valid-palindrome/EstherKim97.py
=> [EstherKim97] Week 1

3sum/easyone-jwlee.go, climbing-stairs/easyone-jwlee.go, construct-binary-tree-from-preorder-and-inorder-traversal/easyone-jwlee.go, decode-ways/easyone-jwlee.go, valid-anagram/easyone-jwlee.go
=> [똘치] Week2

construct-binary-tree-from-preorder-and-inorder-traversal/bus710.go, counting-bits/bus710.rs, valid-anagram/bus710.rs
=> [bus710] Week 02

climbing-stairs/river20s.java, valid-anagram/river20s.java
=> [river20s] WEEK 02

climbing-stairs/EstherKim97.py, valid-anagram/EstherKim97.py
=> [EstherKim97] WEEK 02 

climbing-stairs/5YoonCheol.java, valid-anagram/5YoonCheol.java
=> [YoonCheolOh] WEEK 02 solutions

climbing-stairs/Yjason-K.ts, valid-anagram/Yjason-K.ts
=> [gomgom22] Week 2

3sum/neverlish.go, climbing-stairs/neverlish.go, construct-binary-tree-from-preorder-and-inorder-traversal/neverlish.go, decode-ways/neverlish.go, valid-anagram/neverlish.go
=> [jinho] Week 2

combination-sum/GangBean.java, maximum-subarray/GangBean.java, product-of-array-except-self/GangBean.java, reverse-bits/GangBean.java, two-sum/GangBean.java
=> [GangBean] Week 3

combination-sum/gmlwls96.kt, maximum-subarray/gmlwls96.kt, product-of-array-except-self/gmlwls96.kt, reverse-bits/gmlwls96.kt, two-sum/gmlwls96.kt
=> [gmlwls96] Week3 

combination-sum/donghyeon95.java, maximum-subarray/donghyeon95.java, product-of-array-except-self/donghyeon95.java, reverse-bits/donghyeon95.java, two-sum/donghyeon95.java
=> [donghyeon95] Week3

product-of-array-except-self/higeuni.js, reverse-bits/higeuni.js, two-sum/higeuni.js
=> [khyo] Week3

combination-sum/mike2ox.ts, maximum-subarray/mike2ox.ts, product-of-array-except-self/mike2ox.ts, reverse-bits/mike2ox.ts, two-sum/mike2ox.ts
=> [moonhyeok] Week3

maximum-subarray/YeomChaeeun.ts, product-of-array-except-self/YeomChaeeun.ts, reverse-bits/YeomChaeeun.ts, two-sum/YeomChaeeun.ts
=> [YeomChaeeun] Week 3

combination-sum/thispath98.py, maximum-subarray/thispath98.py, product-of-array-except-self/thispath98.py, reverse-bits/thispath98.py, two-sum/thispath98.py
=> [thispath98] Week 3

combination-sum/taewanseoul.ts, product-of-array-except-self/taewanseoul.ts, reverse-bits/taewanseoul.ts, two-sum/taewanseoul.ts
=> [Wan] Week 3

combination-sum/HodaeSsi.py, maximum-subarray/HodaeSsi.py, product-of-array-except-self/HodaeSsi.py, reverse-bits/HodaeSsi.py, two-sum/HodaeSsi.py
=> [HodaeSsi] Week3

combination-sum/pmjuu.py, maximum-subarray/pmjuu.py, product-of-array-except-self/pmjuu.py, reverse-bits/pmjuu.py, two-sum/pmjuu.py
=> [Lyla] WEEK 03

combination-sum/mmyeon.ts, product-of-array-except-self/mmyeon.ts, two-sum/mmyeon.ts
=> [mallayon] Week 3

product-of-array-except-self/limlimjo.js, reverse-bits/limlimjo.js, two-sum/limlimjo.js
=> [jj7779607] Week3

maximum-subarray/Jeehay28.js, product-of-array-except-self/Jeehay28.js, reverse-bits/Jeehay28.js, two-sum/Jeehay28.js
=> [Jeehay28] Week 03

combination-sum/Zioq.js, product-of-array-except-self/Zioq.js, reverse-bits/Zioq.js, two-sum/Zioq.js
=> [Zioq] Week3

binary-tree-level-order-traversal/Gotprgmer.java
=> [Gotprgmer] Week3

combination-sum/heypaprika.py, maximum-subarray/heypaprika.py, product-of-array-except-self/heypaprika.py, reverse-bits/heypaprika.py, two-sum/heypaprika.py
=> [croucs] Week 03

combination-sum/mintheon.java, product-of-array-except-self/mintheon.java, reverse-bits/mintheon.java, two-sum/mintheon.java
=> [mintheon] Week3

combination-sum/jinah92.py, maximum-subarray/jinah92.py, product-of-array-except-self/jinah92.py, reverse-bits/jinah92.py, two-sum/jinah92.py
=> [jinah92] Week 3

product-of-array-except-self/EcoFriendlyAppleSu.kt, reverse-bits/EcoFriendlyAppleSu.kt, two-sum/EcoFriendlyAppleSu.kt
=> [친환경사과] Week 3

combination-sum/sungjinwi.py, maximum-product-subarray/sungjinwi.py, product-of-array-except-self/sungjinwi.py, reverse-bits/sungjinwi.py, two-sum/sungjinwi.py
=> [suwi] Week 03

3sum/Yjason-K.ts, product-of-array-except-self/Yjason-K.ts, reverse-bits/Yjason-K.ts, two-sum/Yjason-K.ts
=> [gomgom22] Week3

coin-change/jinah92.py, merge-two-sorted-lists/jinah92.py, missing-number/jinah92.py, palindromic-substrings/jinah92.py, word-search/jinah92.py
=> [jinah92] Week 4

coin-change/minji-go.java, combination-sum/minji-go.java, merge-two-sorted-lists/minji-go.java, missing-number/minji-go.java, palindromic-substrings/minji-go.java, word-search/minji-go.java
=> [minji-go] Week 4

coin-change/mmyeon.ts, merge-two-sorted-lists/mmyeon.ts, missing-number/mmyeon.ts, palindromic-substrings/mmyeon.ts, word-search/mmyeon.ts
=> [mallayon] Week 4

merge-two-sorted-lists/bus710.go
=> [bus710] week 04

coin-change/gwbaik9717.js, merge-two-sorted-lists/gwbaik9717.js, missing-number/gwbaik9717.js, palindromic-substrings/gwbaik9717.js, word-search/gwbaik9717.js
=> [ganu] Week4

coin-change/Yjason-K.ts, merge-two-sorted-lists/Yjason-K.ts, missing-number/Yjason-K.ts, palindromic-substrings/Yjason-K.ts, word-search/Yjason-K.ts
=> [gomgom22] Week4

merge-two-sorted-lists/mintheon.java, missing-number/mintheon.java, palindromic-substrings/mintheon.java, word-search/mintheon.java
=> [mintheon] Week 4

coin-change/Jeehay28.js, merge-two-sorted-lists/Jeehay28.js, missing-number/Jeehay28.js, palindromic-substrings/Jeehay28.js, word-search/Jeehay28.js
=> [Jeehay28] Week 4

coin-change/dusunax.py, merge-two-sorted-lists/dusunax.py, missing-number/dusunax.py, palindromic-substrings/dusunax.py, word-search/dusunax.py
=> [SunaDu] Week 4

coin-change/GangBean.java, merge-two-sorted-lists/GangBean.java, missing-number/GangBean.java, palindromic-substrings/GangBean.java, word-search/GangBean.java
=> [GangBean] Week 4

coin-change/gmlwls96.kt, merge-two-sorted-lists/gmlwls96.kt, missing-number/gmlwls96.kt, palindromic-substrings/gmlwls96.kt, word-search/gmlwls96.kt
=> [gmlwls96] Week4

coin-change/thispath98.py, merge-two-sorted-lists/thispath98.py, missing-number/thispath98.py, palindromic-substrings/thispath98.py, word-search/thispath98.py
=> [thispath98] Week 4

coin-change/YeomChaeeun.ts, merge-two-sorted-lists/YeomChaeeun.ts, missing-number/YeomChaeeun.ts
=> [YeomChaeeun] Week 4

merge-two-sorted-lists/limlimjo.js, missing-number/limlimjo.js
=> [jj7779607] Week4

coin-change/forest000014.java, merge-two-sorted-lists/forest000014.java, missing-number/forest000014.java, palindromic-substrings/forest000014.java, word-search/forest000014.java
=> [forest000014] Week 4

merge-two-sorted-lists/donghyeon95.java, missing-number/donghyeon95.java
=> [donghyeon95] Week 4

merge-two-sorted-lists/taewanseoul.ts, missing-number/taewanseoul.ts, word-search/taewanseoul.ts
=> [Wan] Week 4

merge-two-sorted-lists/rivkode.py, missing-number/rivkode.py
=> [rivkode] Week4

merge-two-sorted-lists/Jay-Mo-99.py, missing-number/Jay-Mo-99.py, valid-anagram/Jay-Mo-99.py
=> [Jay-Mo-99] Week 04 

coin-change/ekgns33.java, merge-two-sorted-lists/ekgns33.java, missing-number/ekgns33.java, palindromic-substrings/ekgns33.java, word-search/ekgns33.java
- [] 코드 검토자 1분 이상으로부터 승인을 받으셨다면 PR을 병합해주세요.
=> [byteho0n] Week4

coin-change/jeldo.py, merge-two-sorted-lists/jeldo.py, missing-number/jeldo.py, word-search/jeldo.py
=> [jeldo3] Week4

coin-change/HodaeSsi.py, merge-two-sorted-lists/HodaeSsi.py, missing-number/HodaeSsi.py, palindromic-substrings/HodaeSsi.py, word-search/HodaeSsi.py
늦게 제출하여 죄송합니다.
차주에는 차질없게 진행할 수 있도록 하겠습니다.
=> [HodaeSsi] Week4

best-time-to-buy-and-sell-stock/eunhwa99.java, encode-and-decode-strings/eunhwa99.java, group-anagrams/eunhwa99.java, implement-trie-prefix-tree/eunhwa99.java, word-break/eunhwa99.java
=> [eunhwa99] Week 5

best-time-to-buy-and-sell-stock/jungsiroo.py, group-anagrams/jungsiroo.py, implement-trie-prefix-tree/jungsiroo.py, word-break/jungsiroo.py
=> [jungsiroo] Week 5

best-time-to-buy-and-sell-stock/bus710.go
=> [bus710] week 05

best-time-to-buy-and-sell-stock/GangBean.java, encode-and-decode-strings/GangBean.java, group-anagrams/GangBean.java, implement-trie-prefix-tree/GangBean.java, word-break/GangBean.java
=> [GangBean] Week 5

best-time-to-buy-and-sell-stock/mmyeon.ts, encode-and-decode-strings/mmyeon.ts, group-anagrams/mmyeon.ts, implement-trie-prefix-tree/mmyeon.ts, word-break/mmyeon.ts
=> [mallayon] Week 5

best-time-to-buy-and-sell-stock/ekgns33.java, encode-and-decode-strings/ekgns33.java, group-anagrams/ekgns33.java, implement-trie-prefix-tree/ekgns33.java, word-break/ekgns33.java
=> [byteho0n] Week5

best-time-to-buy-and-sell-stock/forest000014.java, encode-and-decode-strings/forest000014.java, group-anagrams/forest000014.java, implement-trie-prefix-tree/forest000014.java, word-break/forest000014.java
=> [forest000014] Week 5

best-time-to-buy-and-sell-stock/Chaedie.py, group-anagrams/Chaedie.py, implement-trie-prefix-tree/Chaedie.py
=> [Chaedie] Week 5

best-time-to-buy-and-sell-stock/gwbaik9717.js, encode-and-decode-strings/gwbaik9717.js, group-anagrams/gwbaik9717.js, implement-trie-prefix-tree/gwbaik9717.js, word-break/gwbaik9717.js
=> [ganu] Week 5

best-time-to-buy-and-sell-stock/YeomChaeeun.ts, group-anagrams/YeomChaeeun.ts, implement-trie-prefix-tree/YeomChaeeun.ts, word-break/YeomChaeeun.ts
=> [YeomChaeeun] Week 5

best-time-to-buy-and-sell-stock/Yjason-K.ts, encode-and-decode-strings/Yjason-K.ts, group-anagrams/Yjason-K.ts, word-break/Yjason-K.ts
=> [gomgom22] Week5 

best-time-to-buy-and-sell-stock/pmjuu.py, encode-and-decode-strings/pmjuu.py, group-anagrams/pmjuu.py, implement-trie-prefix-tree/pmjuu.py, word-break/pmjuu.py, word-search/pmjuu.py
=> [Lyla] Week 05

best-time-to-buy-and-sell-stock/dusunax.py, encode-and-decode-strings/dusunax.py, group-anagrams/dusunax.py, implement-trie-prefix-tree/dusunax.py, word-break/dusunax.py
=> [SunaDu] Week 5

best-time-to-buy-and-sell-stock/aa601.py, group-anagrams/aa601.py, word-break/aa601.py
=> [yeoju] Week 5 

best-time-to-buy-and-sell-stock/higeuni.js, group-anagrams/higeuni.js, implement-trie-prefix-tree/higeuni.js
=> [khyo] Week 5

best-time-to-buy-and-sell-stock/Jeehay28.js, group-anagrams/Jeehay28.js, implement-trie-prefix-tree/Jeehay28.js, word-break/Jeehay28.js
=> [Jeehay28] WEEK 05

best-time-to-buy-and-sell-stock/mintheon.java, encode-and-decode-strings/mintheon.java, group-anagrams/mintheon.java
=> [mintheon] Week 5

best-time-to-buy-and-sell-stock/jinah92.py, encode-and-decode-strings/jinah92.py, group-anagrams/jinah92.py, implement-trie-prefix-tree/jinah92.py, word-break/jinah92.py
=> [jinah92] Week 5

best-time-to-buy-and-sell-stock/taewanseoul.ts, encode-and-decode-strings/taewanseoul.ts, group-anagrams/taewanseoul.ts
=> [Wan] Week 5

best-time-to-buy-and-sell-stock/heypaprika.py, encode-and-decode-strings/heypaprika.py, group-anagrams/heypaprika.py, implement-trie-prefix-tree/heypaprika.py, word-break/heypaprika.py
=> [croucs] Week : 5

best-time-to-buy-and-sell-stock/EcoFriendlyAppleSu.kt, encode-and-decode-strings/EcoFriendlyAppleSu.kt, group-anagrams/EcoFriendlyAppleSu.kt
=> [친환경사과] Week 5

best-time-to-buy-and-sell-stock/sungjinwi.py, group-anagrams/sungjinwi.py, implement-trie-prefix-tree/sungjinwi.py, word-break/sungjinwi.py
=> [suwi] Week 05

best-time-to-buy-and-sell-stock/limlimjo.js, group-anagrams/limlimjo.js
=> [jj7779607] Week5

best-time-to-buy-and-sell-stock/anniemon.js, encode-and-decode-strings/anniemon.js, group-anagrams/anniemon.js, implement-trie-prefix-tree/anniemon.js
=> [anniemon78] Week5

best-time-to-buy-and-sell-stock/HerrineKim.js, group-anagrams/HerrineKim.js
=> [HerrineKim] Week 5

best-time-to-buy-and-sell-stock/donghyeon95.java, encode-and-decode-strings/donghyeon95.java, group-anagrams/donghyeon95.java, implement-trie-prefix-tree/donghyeon95.java, word-break/donghyeon95.java
=> [donghyeon95] Week5

best-time-to-buy-and-sell-stock/imsosleepy.java, encode-and-decode-strings/imsosleepy.java, group-anagrams/imsosleepy.java, implement-trie-prefix-tree/imsosleepy.java, word-break/imsosleepy.java
=> [ackku] Week 5

best-time-to-buy-and-sell-stock/HodaeSsi.py, encode-and-decode-strings/HodaeSsi.py, group-anagrams/HodaeSsi.py, implement-trie-prefix-tree/HodaeSsi.py, word-break/HodaeSsi.py
=> [HodaeSsi] Week 5

container-with-most-water/taewanseoul.ts, valid-parentheses/taewanseoul.ts
=> [Wan] Week 6

container-with-most-water/mmyeon.ts, design-add-and-search-words-data-structure/mmyeon.ts, longest-increasing-subsequence/mmyeon.ts, spiral-matrix/mmyeon.ts, valid-parentheses/mmyeon.ts
=> [mallayon] Week 6

valid-parentheses/bus710.go
=> [bus710] Week 06

container-with-most-water/gwbaik9717.js, design-add-and-search-words-data-structure/gwbaik9717.js, longest-increasing-subsequence/gwbaik9717.js, spiral-matrix/gwbaik9717.js, valid-parentheses/gwbaik9717.js
=> [ganu] Week6

container-with-most-water/jungsiroo.py, design-add-and-search-words-data-structure/jungsiroo.py, spiral-matrix/jungsiroo.py, valid-parentheses/jungsiroo.py
=> [jungsiroo] Week 06

container-with-most-water/HerrineKim.js, valid-parentheses/HerrineKim.js
=> [HerrineKim] Week 6

container-with-most-water/jinah92.py, design-add-and-search-words-data-structure/jinah92.py, longest-increasing-subsequence/jinah92.py, valid-parentheses/jinah92.py
=> [jinah92] Week 6

container-with-most-water/yeeZinu.js, design-add-and-search-words-data-structure/yeeZinu.js
=> [호돌이] Week 6

container-with-most-water/jdy8739.js, spiral-matrix/jdy8739.js, valid-parentheses/jdy8739.js
=> [jdy8739] Week6

container-with-most-water/ekgns33.java, design-add-and-search-words-data-structure/ekgns33.java, longest-increasing-subsequence/ekgns33.java, spiral-matrix/ekgns33.java, valid-parentheses/ekgns33.java
=> [byteho0n] Week 6

design-add-and-search-words-data-structure/anniemon.js, valid-parentheses/anniemon.js
=> [anniemon78] Week6

container-with-most-water/YeomChaeeun.ts, longest-increasing-subsequence/YeomChaeeun.ts, spiral-matrix/YeomChaeeun.ts, valid-parentheses/YeomChaeeun.ts
=> [YeomChaeeun] Week 6

container-with-most-water/Yjason-K.ts, encode-and-decode-strings/Yjason-K.ts, longest-increasing-subsequence/Yjason-K.ts, spiral-matrix/Yjason-K.ts, valid-parentheses/Yjason-K.ts
=> [gomgom22] Week6

container-with-most-water/limlimjo.js, valid-parentheses/limlimjo.js
=> [jj7779607] Week6

container-with-most-water/dusunax.py, design-add-and-search-words-data-structure/dusunax.py, longest-increasing-subsequence/dusunax.py, spiral-matrix/dusunax.py, valid-parentheses/dusunax.py
=> [SunaDu] Week 6

container-with-most-water/Jeehay28.js, design-add-and-search-words-data-structure/Jeehay28.js, longest-increasing-subsequence/Jeehay28.js, spiral-matrix/Jeehay28.js, valid-parentheses/Jeehay28.js
=> [Jeehay28] WEEK 06

container-with-most-water/Chaedie.py, design-add-and-search-words-data-structure/Chaedie.py, encode-and-decode-strings/Chaedie.py, longest-increasing-subsequence/Chaedie.py, spiral-matrix/Chaedie.py, valid-parentheses/Chaedie.py
=> [Chaedie] Week 6

container-with-most-water/pmjuu.py, design-add-and-search-words-data-structure/pmjuu.py, longest-increasing-subsequence/pmjuu.py, spiral-matrix/pmjuu.py, valid-parentheses/pmjuu.py
=> [Lyla] Week 06

container-with-most-water/EcoFriendlyAppleSu.kt, design-add-and-search-words-data-structure/EcoFriendlyAppleSu.kt, valid-parentheses/EcoFriendlyAppleSu.kt
=> [친환경사과] Week 6

container-with-most-water/GangBean.java, valid-parentheses/GangBean.java
=> [GangBean] Week 6

container-with-most-water/lledellebell.ts, valid-parentheses/lledellebell.ts
=> [dd_._._bb] Week 6

container-with-most-water/jeldo.py, spiral-matrix/jeldo.py, valid-parentheses/jeldo.py
=> [jeldo3] Week6

container-with-most-water/sungjinwi.py, longest-increasing-subsequence/sungjinwi.py, spiral-matrix/sungjinwi.py, valid-parentheses/sungjinwi.py
=> [suwi] Week06

container-with-most-water/imsosleepy.java, design-add-and-search-words-data-structure/imsosleepy.java, longest-increasing-subsequence/imsosleepy.java, spiral-matrix/imsosleepy.java, valid-parentheses/imsosleepy.java
=> [Ackku] Week 6

container-with-most-water/aa601.py, longest-increasing-subsequence/aa601.py, valid-parentheses/aa601.py
=> [yeoju] WEEK6

container-with-most-water/HodaeSsi.py, design-add-and-search-words-data-structure/HodaeSsi.py, longest-increasing-subsequence/HodaeSsi.py, spiral-matrix/HodaeSsi.py, valid-parentheses/HodaeSsi.py
=> [HodaeSsi] week 06

longest-substring-without-repeating-characters/mmyeon.ts, number-of-islands/mmyeon.ts, reverse-linked-list/mmyeon.ts, set-matrix-zeroes/mmyeon.ts, unique-paths/mmyeon.ts
=> [mallayon] Week 7

longest-substring-without-repeating-characters/gmlwls96.kt, number-of-islands/gmlwls96.kt, reverse-linked-list/gmlwls96.kt, set-matrix-zeroes/gmlwls96.kt, unique-paths/gmlwls96.kt
=> [gmlwls96] Week7

longest-substring-without-repeating-characters/sungjinwi.py, number-of-islands/sungjinwi.py, reverse-linked-list/sungjinwi.py, set-matrix-zeroes/sungjinwi.py, unique-paths/sungjinwi.py
=> [suwi] Week 07

longest-substring-without-repeating-characters/lledellebell.ts, reverse-linked-list/lledellebell.ts
=> [dd_._._bb] Week 07 

longest-substring-without-repeating-characters/pmjuu.py, number-of-islands/pmjuu.py, reverse-linked-list/pmjuu.py, set-matrix-zeroes/pmjuu.py, unique-paths/pmjuu.py
=> [Lyla] Week 07

reverse-linked-list/bus710.go
=> [bus710] Week 07

longest-substring-without-repeating-characters/gwbaik9717.js, number-of-islands/gwbaik9717.js, reverse-linked-list/gwbaik9717.js, set-matrix-zeroes/gwbaik9717.js, unique-paths/gwbaik9717.js
=> [ganu] Week 07

longest-substring-without-repeating-characters/EcoFriendlyAppleSu.kt, number-of-islands/EcoFriendlyAppleSu.kt, reverse-linked-list/EcoFriendlyAppleSu.kt, set-matrix-zeroes/EcoFriendlyAppleSu.kt, unique-paths/EcoFriendlyAppleSu.kt
=> [친환경사과] Week 7

longest-substring-without-repeating-characters/Yjason-K.ts, number-of-islands/Yjason-K.ts, reverse-linked-list/Yjason-K.ts, set-matrix-zeroes/Yjason-K.ts, unique-paths/Yjason-K.ts
=> [Week7] gomgom22

longest-substring-without-repeating-characters/jdy8739.js, number-of-islands/jdy8739.js, reverse-linked-list/jdy8739.js, set-matrix-zeroes/jdy8739.js, unique-paths/jdy8739.js
=> [jdy8739] Week 7

longest-substring-without-repeating-characters/ekgns33.java, number-of-islands/ekgns33.java, reverse-linked-list/ekgns33.java, set-matrix-zeroes/ekgns33.java, unique-paths/ekgns33.java
=> [byteho0n] - Week 7

number-of-islands/HerrineKim.js, set-matrix-zeroes/HerrineKim.js
=> [HerrineKim] Week 7

longest-substring-without-repeating-characters/higeuni.js, number-of-islands/higeuni.js, reverse-linked-list/higeuni.js, unique-paths/higeuni.js
=> [khyo] Week 7

longest-substring-without-repeating-characters/YeomChaeeun.ts, number-of-islands/YeomChaeeun.ts, reverse-linked-list/YeomChaeeun.ts
=> [YeomChaeeun] Week 7

reverse-linked-list/jinah92.py
=> [jinah92] Week 7

longest-substring-without-repeating-characters/jungsiroo.py, number-of-islands/jungsiroo.py, reverse-linked-list/jungsiroo.py, set-matrix-zeroes/jungsiroo.py, unique-paths/jungsiroo.py
=> [jungsiroo] Week 7

reverse-linked-list/yeeZinu.js
=> [hodoli] Week 7

longest-substring-without-repeating-characters/Jeehay28.js, number-of-islands/Jeehay28.js, reverse-linked-list/Jeehay28.js, set-matrix-zeroes/Jeehay28.js, unique-paths/Jeehay28.js
=> [Jeehay28] WEEK 07

longest-substring-without-repeating-characters/dusunax.py, number-of-islands/dusunax.py, reverse-linked-list/dusunax.py, set-matrix-zeroes/dusunax.py, unique-paths/dusunax.py
=> [SunaDu] - Week 7

longest-substring-without-repeating-characters/yolophg.py, number-of-islands/yolophg.py, reverse-linked-list/yolophg.py, set-matrix-zeroes/yolophg.py, unique-paths/yolophg.py
=> [Helena] Week 7

longest-substring-without-repeating-characters/Chaedie.py, number-of-islands/Chaedie.py, reverse-linked-list/Chaedie.py, set-matrix-zeroes/Chaedie.py, unique-paths/Chaedie.py
=> [Chaedie] Week 7

longest-substring-without-repeating-characters/aa601.py, number-of-islands/aa601.py, reverse-linked-list/aa601.py, set-matrix-zeroes/aa601.py, unique-paths/aa601.py
=> [yeoju] Week 7

reverse-linked-list/mintheon.java
=> [mintheon] Week 7

longest-substring-without-repeating-characters/kdh-92.java, number-of-islands/kdh-92.java, reverse-linked-list/kdh-92.java, unique-paths/kdh-92.java
=> [권동현] Week 7

reverse-linked-list/limlimjo.js
=> [jj7779607] Week7

longest-substring-without-repeating-characters/donghyeon95.java, number-of-islands/donghyeon95.java, reverse-linked-list/donghyeon95.java, set-matrix-zeroes/donghyeon95.java, unique-paths/donghyeon95.java
=> [donghyeon95] Week 7

longest-substring-without-repeating-characters/imsosleepy.java, number-of-islands/imsosleepy.java, reverse-linked-list/imsosleepy.java, set-matrix-zeroes/imsosleepy.java, unique-paths/imsosleepy.java
=> [Akku] week 7

longest-substring-without-repeating-characters/neverlish.go, number-of-islands/neverlish.go, reverse-linked-list/neverlish.go
=> [jinho] week 07

clone-graph/Jeehay28.js, longest-common-subsequence/Jeehay28.js, longest-repeating-character-replacement/Jeehay28.js, number-of-1-bits/Jeehay28.js, sum-of-two-integers/Jeehay28.js
=> [Jeehay28] WEEK 08

clone-graph/forest000014.java, longest-common-subsequence/forest000014.java, longest-repeating-character-replacement/forest000014.java, number-of-1-bits/forest000014.java, sum-of-two-integers/forest000014.java
=> [forest000014] Week 8

clone-graph/gwbaik9717.js, longest-common-subsequence/gwbaik9717.js, longest-repeating-character-replacement/gwbaik9717.js, number-of-1-bits/gwbaik9717.js
=> [ganu] Week 8

design-add-and-search-words-data-structure/GangBean.java, longest-increasing-subsequence/GangBean.java, longest-substring-without-repeating-characters/GangBean.java, number-of-1-bits/GangBean.java, number-of-islands/GangBean.java, reverse-linked-list/GangBean.java, set-matrix-zeroes/GangBean.java, spiral-matrix/GangBean.java, unique-paths/GangBean.java
=> [GangBean] Week 8

longest-common-subsequence/YeomChaeeun.ts, number-of-1-bits/YeomChaeeun.ts, sum-of-two-integers/YeomChaeeun.ts
=> [YeomChaeeun] Week 8

clone-graph/dusunax.py, longest-common-subsequence/dusunax.py, longest-repeating-character-replacement/dusunax.py, number-of-1-bits/dusunax.py, sum-of-two-integers/dusunax.py
=> [SunaDu] Week8

number-of-1-bits/bus710.rs
=> [bus710] Week 08

clone-graph/EcoFriendlyAppleSu.kt, longest-repeating-character-replacement/EcoFriendlyAppleSu.kt, number-of-1-bits/EcoFriendlyAppleSu.kt
=> [친환경사과] week 8

clone-graph/Chaedie.py, longest-common-subsequence/Chaedie.py, longest-repeating-character-replacement/Chaedie.py, longest-substring-without-repeating-characters/Chaedie.py, number-of-1-bits/Chaedie.py, reverse-linked-list/Chaedie.py, sum-of-two-integers/Chaedie.py, unique-paths/Chaedie.py
=> [Chaedie] Week 8

clone-graph/yolophg.py, longest-common-subsequence/yolophg.py, longest-repeating-character-replacement/yolophg.py, number-of-1-bits/yolophg.py, sum-of-two-integers/yolophg.py
=> [Helena] Week 8

clone-graph/sungjinwi.py, longest-repeating-character-replacement/sungjinwi.py, number-of-1-bits/sungjinwi.py, sum-of-two-integers/sungjinwi.py
=> [suwi] Week 08

longest-common-subsequence/aa601.py, longest-repeating-character-replacement/aa601.py, number-of-1-bits/aa601.py, sum-of-two-integers/aa601.py
=> [yeoju] Week 8

clone-graph/ekgns33.java, longest-common-subsequence/ekgns33.java, longest-repeating-character-replacement/ekgns33.java, number-of-1-bits/ekgns33.java, sum-of-two-integers/ekgns33.java
=> [byteho0n] Week 8

longest-common-subsequence/anniemon.js, number-of-1-bits/anniemon.js
=> [anniemon78] Week8

find-minimum-in-rotated-sorted-array/KwonNayeon.py, linked-list-cycle/KwonNayeon.py, maximum-product-subarray/KwonNayeon.py, minimum-window-substring/KwonNayeon.py, pacific-atlantic-water-flow/KwonNayeon.py
=> [KwonNayeon] Week 9

find-minimum-in-rotated-sorted-array/gwbaik9717.js, linked-list-cycle/gwbaik9717.js, maximum-product-subarray/gwbaik9717.js, minimum-window-substring/gwbaik9717.js, pacific-atlantic-water-flow/gwbaik9717.js
=> [ganu] Week9

find-minimum-in-rotated-sorted-array/YeomChaeeun.ts, linked-list-cycle/YeomChaeeun.ts, maximum-product-subarray/YeomChaeeun.ts
=> [YeomChaeeun] Week 9

linked-list-cycle/bus710.go
=> [bus710] Week 09

find-minimum-in-rotated-sorted-array/Chaedie.py, linked-list-cycle/Chaedie.py, maximum-product-subarray/Chaedie.py, pacific-atlantic-water-flow/Chaedie.py
=> [Chaedie] Week 9

find-minimum-in-rotated-sorted-array/yolophg.py, linked-list-cycle/yolophg.py, maximum-product-subarray/yolophg.py, minimum-window-substring/yolophg.py, pacific-atlantic-water-flow/yolophg.py
=> [Helena] Week 9

find-minimum-in-rotated-sorted-array/Jeehay28.js, linked-list-cycle/Jeehay28.js, maximum-product-subarray/Jeehay28.js, minimum-window-substring/Jeehay28.js, pacific-atlantic-water-flow/Jeehay28.js
=> [Jeehay28] WEEK 09

find-minimum-in-rotated-sorted-array/ekgns33.java, linked-list-cycle/ekgns33.java, maximum-product-subarray/ekgns33.java, minimum-window-substring/ekgns33.java, pacific-atlantic-water-flow/ekgns33.java
=> [byteho0n] Week 09

linked-list-cycle/EcoFriendlyAppleSu.kt, longest-common-subsequence/EcoFriendlyAppleSu.kt
=> [친환경사과] week9

find-minimum-in-rotated-sorted-array/pmjuu.py, linked-list-cycle/pmjuu.py, maximum-product-subarray/pmjuu.py, pacific-atlantic-water-flow/pmjuu.py
=> [Lyla] Week 09

clone-graph/forest000014.java, find-minimum-in-rotated-sorted-array/forest000014.java, linked-list-cycle/forest000014.java, maximum-product-subarray/forest000014.java
=> [forest000014] Week 09

find-minimum-in-rotated-sorted-array/mintheon.java, linked-list-cycle/mintheon.java, maximum-product-subarray/mintheon.java
=> [mintheon] Week 09

find-minimum-in-rotated-sorted-array/mike2ox.ts, linked-list-cycle/mike2ox.ts, maximum-product-subarray/mike2ox.ts, pacific-atlantic-water-flow/mike2ox.ts
=> [moonhyeok] Week9

linked-list-cycle/limlimjo.js
=> [jj7779607] Week9

linked-list-cycle/thispath98.py
=> [thispath98] Week 9

find-minimum-in-rotated-sorted-array/neverlish.go, linked-list-cycle/neverlish.go, maximum-product-subarray/neverlish.go
=> [jinho] week 9

find-minimum-in-rotated-sorted-array/sungjinwi.py, linked-list-cycle/sungjinwi.py, maximum-product-subarray/sungjinwi.py, maximum-subarray/sungjinwi.py, minimum-window-substring/sungjinwi.py, pacific-atlantic-water-flow/sungjinwi.py
=> [suwi] Week 09

find-minimum-in-rotated-sorted-array/aa601.py, linked-list-cycle/aa601.py, maximum-product-subarray/aa601.py, pacific-atlantic-water-flow/aa601.py
=> [yeoju] Week 9

course-schedule/gwbaik9717.js, invert-binary-tree/gwbaik9717.js, jump-game/gwbaik9717.js, merge-k-sorted-lists/gwbaik9717.js, search-in-rotated-sorted-array/gwbaik9717.js
=> [ganu] Week 10
