README.md

기존 초대 링크는 서버에서 튕기는 현상이 있어서, 기존에 잘 되고 있던 초대 링크로 수정

디스코드 초대 링크 수정

---

README.md

Readme.md 오타 수정, 스터디 멤버 링크

---

.gitignore

[saysimple] gitignore에 에디터 설정 추가

---

CONTRIBUTING.md
README.md

- readme.md 와 contributing.md 문서에 링크만 있는 곳들이 있음.
- readme.md 하단에 contributing.md 로 가는 링크가 잘못 연결되어 있음.
- readme.md 와 contributing.md 문서에 있는 링크들에 대해 설명과 함께 연결되도록 수정
- 잘못 연결된 링크 수정

readme.md 및 contributing.md 개선

---

invert-binary-tree/README.md
linked-list-cycle/README.md
merge-two-sorted-lists/README.md
reverse-linked-list/README.md
valid-parentheses/REAMEE.md

https://github.com/DaleStudy/leetcode-study/pull/39#issuecomment-2092610758 에서 제안해주신 의견을 반영하여 2주차 문제에 대한 폴더를 생성합니다. 폴더만 생성하면 Git이 추적을 못하기 때문에 `README.md` 파일을 각 폴더에 생성하였습니다.

2주차 문제 폴더 추가

---

CONTRIBUTING.md
README.md

제가 방금 참가 신청 글을 이슈에서 토론으로 옮겨서 README.md 파일에 있는 링크도 업데이트합니다.

참가 신청 링크 업데이트

---

invert-binary-tree/yolophg.js
linked-list-cycle/yolophg.js
merge-two-sorted-lists/yolophg.js
reverse-linked-list/yolophg.js
valid-parentheses/yolophg.js

Included as follows :
- Valid Parentheses
- Reverse Linked List
- Merge Two Sorted Lists
- Linked List Cycle
- Invert Binary Tree

[Helena] Week 2 solutions

---

best-time-to-buy-and-sell-stock/README.md
climbing-stairs/README.md
contains-duplicate/README.md
maximum-depth-of-binary-tree/README.md
meeting-rooms/README.md
same-tree/README.md
subtree-of-another-tree/README.md
two-sum/README.md
valid-anagram/README.md
valid-palindrome/README.md

2주차 문제 폴더에만 README.md 파일이 추가되어 있어서, 1주차와 3주차 폴더에도 README.md 파일을 추가합니다. 각 폴더에 문제와 해설에 대한 링크가 있으니 편하다는 피드백이 있었거든요.

누락된 README.md 파일 추가

---

climbing-stairs/dev-jonghoonpark.md
maximum-depth-of-binary-tree/dev-jonghoonpark.md
meeting-rooms/dev-jonghoonpark.md
same-tree/dev-jonghoonpark.md
subtree-of-another-tree/dev-jonghoonpark.md

[박종훈] 3주차 답안 제출

---

graph-valid-tree/WhiteHyun.swift
house-robber-ii/WhiteHyun.swift
house-robber/WhiteHyun.swift
longest-palindromic-substring/WhiteHyun.swift
number-of-connected-components-in-an-undirected-graph/WhiteHyun.swift

- Time Complexity: $O(N)$
- Space Complexity: $O(N)$
완전 연결된 그래프의 edge의 수는 `vertex의 개수 - 1`이어야합니다. 만약 맞을경우 `dfs`를 통해 방문 노드가 `n`만큼 발생했는지를 구하여 풀이했습니다.
- Time Complexity: $O(N)$
- Space Complexity: $O(N)$
연결된 그래프의 그룹을 찾는 문제입니다. 방문되지 않는 노드를 선택하여 DFS를 돌리고, 그룹개수를 1 증가시키는 방법으로 구현했습니다.
- Time Complexity: $O(N)$
처음에는 Dynamic programming으로 공간복잡도 O(N)으로 풀이했으나 달레님의 풀이를 보며 공간복잡도 O(1)로 고쳐보았습니다. :)
- Time Complexity: $O(N)$
원형으로 이루어져있기 때문에 첫 번째 집을 털 경우 다음 집과 마지막은 절대 털 수 없고, 첫 번째 집을 털지 않은 경우 마지막 집은 털 수 있습니다.
첫 번째 집을 털 경우라면 `House Robber I`의 코드에서 마지막 요소만을 제외한 만큼 반복하면 되고,
첫 번째 집을 털지 않는 경우라면 `House Robber I`의 코드에서 첫 번째 요소를 제외한 만큼 반복하면 됩니다.
이 두 가지 값으로 최댓값을 비교하여 풀이했습니다.
- Time Complexity: $O(N^2)$
- Space Complexity: $O(N)$
> swift는 문자열을 처리할 일이 있다면 배열로 …

[Hyun] Week 10 Solution Explanation

---

merge-k-sorted-lists/README.md
minimum-window-substring/README.md
set-matrix-zeroes/README.md
spiral-matrix/README.md
sum-of-two-integers/README.md

어제 모임 때 Hard 문제에 대해서 논의를 했었는데요.
대다수의 의견이 효용이 낮아서 풀지 말자였기 때문에, 모두 Hard 문제로 이루어진 15주차는 진행하지 않기로 결정하였습니다.
따라서 이번에 올려드리는 문제가 1기의 마지막 주차 문제가 될 것 같습니다.
그동안 수고 많으셨고 조금만 더 힘내셔서 다들 유종의 미를 거두셨으면 좋겠습니다.

14주차 문제 폴더 추가

---

alien-dictionary/README.md
binary-tree-maximum-path-sum/README.md
find-median-from-data-stream/README.md
serialize-and-deserialize-binary-tree/README.md
word-search-ii/README.md

@dev-jonghoonpark 님께서 마지막 5문제까지 푸시려는 것 같아서 미리 폴더 만들어 둡니다 ㅋㅋ
스터디 2기 때는 Hard 문제도 포함되어 있으니 어차피 필요한 폴더이기는 합니다.

15주차 문제 폴더 추가

---

contains-duplicate/0-chan.ts
number-of-1-bits/0-chan.ts

[0-chan] Week 1

---

climbing-stairs/hwanmini.js
combination-sum/hwanmini.js
two-sum/hwanmini.js

[환미니니] Week3 문제풀이

---

longest-repeating-character-replacement/sunjae95.js
merge-two-sorted-lists/sunjae95.js

과제전형으로 에너지를 모두 소비해 문제풀이 미흡 이슈입니다...🥲

[선재] WEEK08 Solution

---

longest-substring-without-repeating-characters/sun912.py
number-of-islands/sun912.py
reverse-linked-list/sun912.py

[sun] WEEK7

---

find-minimum-in-rotated-sorted-array/hwanmini.js
linked-list-cycle/hwanmini.js
maximum-subarray/hwanmini.js

[환미니니] Week9 Solutions

---

number-of-connected-components-in-an-undirected-graph/hwanmini.js
same-tree/hwanmini.js

[환미니니] Week12 Solutions

---

house-robber/mangodm-web.py
meeting-rooms/mangodm-web.py

[mangodm-web] Week13 Solutions

---

binary-tree-level-order-traversal/HC-kang.ts
house-robber-ii/HC-kang.ts
meeting-rooms-ii/HC-kang.ts
reverse-bits/HC-kang.ts
word-search-ii/HC-kang.ts

[강희찬] WEEK 14 Solution

---

reverse-bits/gitsunmin.ts

[gitsunmin] WEEK 14 Solutions

---

contains-duplicate/MrKeeplearning.java
valid-palindrome/MrKeeplearning.java

[MrKeeplearning] Week1

---

reverse-bits/anniemon.js
two-sum/anniemon.js

[anniemon78] Week3

---

combination-sum/neverlish.go
maximum-subarray/neverlish.go
product-of-array-except-self/neverlish.go
reverse-bits/neverlish.go
two-sum/neverlish.go

[jinho] Week 3

---

reverse-bits/river20s.java
two-sum/river20s.java

[river20s] WEEK 03

---

two-sum/bus710.go

크리스마스라 더 시간 내기가 어려운 상황 입니다.
스터디 짤림 방지를 위해 하나만 급히 풀어서 냅니다.
즐거운 크리스마스 되세요~

[bus710] week 03

---

combination-sum/gwbaik9717.js
maximum-subarray/gwbaik9717.js
product-of-array-except-self/gwbaik9717.js
reverse-bits/gwbaik9717.js
two-sum/gwbaik9717.js

[ganu] Week3

---

product-of-array-except-self/aa601.py
reverse-bits/aa601.py
two-sum/aa601.py

[yeoju] Week 3

---

coin-change/pmjuu.py
merge-two-sorted-lists/pmjuu.py
missing-number/pmjuu.py
palindromic-substrings/pmjuu.py
word-search/pmjuu.py

[Lyla] Week 04

---

merge-two-sorted-lists/anniemon.js
missing-number/anniemon.js

[anniemon78] Week4

---

merge-two-sorted-lists/changchanghwang.go

[Arthur] week 4

---

coin-change/neverlish.go
merge-two-sorted-lists/neverlish.go
missing-number/neverlish.go
palindromic-substrings/neverlish.go
word-search/neverlish.go

요번 주 휴가를 보내느라 제출이 늦어졌네요. 리뷰해주실 분들 미리 감사드립니다 🙇

[jinho] Week 04

---

merge-two-sorted-lists/yoonthecoder.js
missing-number/yoonthecoder.js
two-sum/yoonthecoder.js

[yoonthecoder] Week 4

---

merge-two-sorted-lists/mike2ox.ts
missing-number/mike2ox.ts

[moonhyeok] Week 4

---

merge-two-sorted-lists/higeuni.js
missing-number/higeuni.js
word-search/higeuni.js

[khyo] Week 4

---

best-time-to-buy-and-sell-stock/choidabom.ts
encode-and-decode-strings/choidabom.ts
group-anagrams/choidabom.ts

[choidabom] Week 5

---

best-time-to-buy-and-sell-stock/jeldo.py
group-anagrams/jeldo.py

[jeldo3] Week5

---

container-with-most-water/neverlish.go
longest-increasing-subsequence/neverlish.go
valid-parentheses/neverlish.go

[jinho] week 06

---

container-with-most-water/higeuni.js
longest-increasing-subsequence/higeuni.js
valid-parentheses/higeuni.js

[khyo] Week 6

---

longest-substring-without-repeating-characters/jeldo.py
number-of-islands/jeldo.py
reverse-linked-list/jeldo.py
set-matrix-zeroes/jeldo.py
unique-paths/jeldo.py

[jeldo] Week 7

---

longest-substring-without-repeating-characters/taewanseoul.ts
reverse-linked-list/taewanseoul.ts

[Wan] Week 7

---

clone-graph/pmjuu.py
longest-common-subsequence/pmjuu.py
longest-repeating-character-replacement/pmjuu.py
number-of-1-bits/pmjuu.py
sum-of-two-integers/pmjuu.py

[Lyla] Week 08

---

number-of-1-bits/limlimjo.js

[jj7779607] Week8

---

number-of-1-bits/gmlwls96.kt

[gmlwls96] Week8

---

longest-repeating-character-replacement/donghyeon95.java
number-of-1-bits/donghyeon95.java

[donghyeon95] Week8

---

find-minimum-in-rotated-sorted-array/imsosleepy.java
linked-list-cycle/imsosleepy.java
maximum-product-subarray/imsosleepy.java
minimum-window-substring/imsosleepy.java
pacific-atlantic-water-flow/imsosleepy.java

[Ackku] Week 9

---

course-schedule/ekgns33.java
invert-binary-tree/ekgns33.java
jump-game/ekgns33.java
merge-k-sorted-lists/ekgns33.java
search-in-rotated-sorted-array/ekgns33.java

[byteho0n] - Week 10

---

invert-binary-tree/limlimjo.js

[jj7779607] Week10

---

invert-binary-tree/taewanseoul.ts

[Wan] Week 10

---

invert-binary-tree/mintheon.java
search-in-rotated-sorted-array/mintheon.java

[mintheon] Week10

---

maximum-depth-of-binary-tree/Yjason-K.ts
merge-intervals/Yjason-K.ts

[gomgom22] Weel11

---

same-tree/bus710.go

[bus710] Week 12

---

binary-tree-level-order-traversal/Yjason-K.ts
counting-bits/Yjason-K.ts
house-robber-ii/Yjason-K.ts

[gomgom22] Week14

---

counting-bits/aa601.py
house-robber-ii/aa601.py

[yeoju] Week 14

---

counting-bits/limlimjo.js

[jj7779607] Week14

---

binary-tree-level-order-traversal/Jeehay28.js
counting-bits/Jeehay28.js
house-robber-ii/Jeehay28.js
word-search-ii/Jeehay28.js

[Jeehay28] WEEK 14

---

subtree-of-another-tree/bus710.go

[bus710] Week 15

---

README.md

README.md에 스터디 4기 정보를 추가하였습니다.

README.md에 스터디 4기 정보 추가

---

contains-duplicate/runnz121.java
house-robber/runnz121.java
longest-consecutive-sequence/runnz121.java
top-k-frequent-elements/runnz121.java
two-sum/runnz121.java

[runnz121] WEEK 01 solutions

---

contains-duplicate/mike2ox.ts
house-robber/mike2ox.ts
longest-consecutive-sequence/mike2ox.ts
top-k-frequent-elements/mike2ox.ts
two-sum/mike2ox.ts

[moonhyeok song] Week 01 solution

---

house-robber/anniemon.js

[annniemon78] Week 01

---

contains-duplicate/byol-han.js
house-robber/byol-han.js
longest-consecutive-sequence/byol-han.js
top-k-frequent-elements/byol-han.js
two-sum/byol-han.js

[byol-han] WEEK 01 solutions

---

contains-duplicate/moonjonghoo.js
house-robber/moonjonghoo.js
longest-consecutive-sequence/moonjonghoo.js
top-k-frequent-elements/moonjonghoo.js
two-sum/moonjonghoo.js

[Moonjonghoo] WEEK 01 solutions

---

contains-duplicate/itschrisjang.java

[itschrisjang] WEEK 01 solutions

---

contains-duplicate/nrudev.ts
longest-consecutive-sequence/nrudev.ts
top-k-frequent-elements/nrudev.ts
two-sum/nrudev.ts

[nrudev] WEEK 01 solutions

---

3sum/HoonDongKang.ts
climbing-stairs/HoonDongKang.ts
top-k-frequent-elements/HoonDongKang.ts
valid-anagram/HoonDongKang.ts
validate-binary-search-tree/HoonDongKang.ts

[HoonDongKang] WEEK 02 solutions

---

product-of-array-except-self/anniemon.js

[anniemon78] week 2

---

number-of-1-bits/nrudev.ts
valid-palindrome/nrudev.ts

[nrudev] WEEK 03 solutions

---

number-of-1-bits/sukyoungshin.ts
valid-palindrome/sukyoungshin.ts

[sukyoungshin] WEEK 03

---

number-of-1-bits/seungseung88.js
valid-palindrome/seungseung88.js

[seungseung88] Week 03 solutions

---

number-of-1-bits/sm9171.java
valid-palindrome/sm9171.java

[sm9171] Week 03 solutions 

---

number-of-1-bits/lhc0506.js
valid-palindrome/lhc0506.js

[lhc0506] Week 03 solutions

---

valid-palindrome/JEONGBEOMKO.java

[JEONGBEOMKO] Week 03 Solutions

---

find-minimum-in-rotated-sorted-array/sukyoungshin.ts
maximum-depth-of-binary-tree/sukyoungshin.ts
merge-two-sorted-lists/sukyoungshin.ts

[sukyoungshin] WEEK04

---

coin-change/JEONGBEOMKO.java
find-minimum-in-rotated-sorted-array/JEONGBEOMKO.java
maximum-depth-of-binary-tree/JEONGBEOMKO.java
merge-two-sorted-lists/JEONGBEOMKO.java
word-search/JEONGBEOMKO.java

[JEONGBEOMKO] Week 04 Solutions

---

coin-change/sora0319.java
find-minimum-in-rotated-sorted-array/sora0319.java
maximum-depth-of-binary-tree/sora0319.java
merge-two-sorted-lists/sora0319.java
word-search/sora0319.java

[sora0319] Week 04 Solutions

---

longest-substring-without-repeating-characters/printjin-gmailcom.py
number-of-islands/printjin-gmailcom.py
reverse-linked-list/printjin-gmailcom.py
set-matrix-zeroes/printjin-gmailcom.py
unique-paths/printjin-gmailcom.py

[printjin-gmailcom] Week 7 Solutions

---

valid-parentheses/JustHm.swift

[JustHm] Week 06 Solutions

---

longest-substring-without-repeating-characters/moonjonghoo.js
reverse-linked-list/moonjonghoo.js

[moonjonghoo] Week 07 Solutions

---

longest-substring-without-repeating-characters/sejineer.py
number-of-islands/sejineer.py
reverse-linked-list/sejineer.py

[sejineer] Week 07 solutions

---

reverse-linked-list/crumbs22.cpp

[crumbs22] Week07 solutions

---

reverse-bits/jinhyungrhee.java

[jinhyunghree] Week 8 solutions

---

clone-graph/hsskey.js
longest-common-subsequence/hsskey.js
longest-repeating-character-replacement/hsskey.js
palindromic-substrings/hsskey.js
reverse-bits/hsskey.js

[hsskey] Week 08 Solutions

---

course-schedule/printjin-gmailcom.py
invert-binary-tree/printjin-gmailcom.py
jump-game/printjin-gmailcom.py
merge-k-sorted-lists/printjin-gmailcom.py
search-in-rotated-sorted-array/printjin-gmailcom.py

[printjin-gmailcom] Week 10 Solutions

---

course-schedule/seungriyou.py
invert-binary-tree/seungriyou.py
jump-game/seungriyou.py
merge-k-sorted-lists/seungriyou.py
search-in-rotated-sorted-array/seungriyou.py

[seungriyou] Week 10 Solutions

---

course-schedule/Tessa1217.java
invert-binary-tree/Tessa1217.java
jump-game/Tessa1217.java
merge-k-sorted-lists/Tessa1217.java
search-in-rotated-sorted-array/Tessa1217.java

[Tessa1217] Week 10 Solutions

---

course-schedule/hoyeongkwak.ts
invert-binary-tree/hoyeongkwak.ts
jump-game/hoyeongkwak.ts
merge-k-sorted-lists/hoyeongkwak.ts
search-in-rotated-sorted-array/hoyeongkwak.ts

[hoyeongkwak] week 10 solutions

---

binary-tree-maximum-path-sum/hoyeongkwak.ts
merge-intervals/hoyeongkwak.ts
missing-number/hoyeongkwak.ts
reorder-list/hoyeongkwak.ts

[hoyeongkwak] Week 11 Solutions

---

non-overlapping-intervals/Jeehay28.ts
remove-nth-node-from-end-of-list/Jeehay28.ts
same-tree/Jeehay28.ts
serialize-and-deserialize-binary-tree/Jeehay28.ts

[Jeehay28] WEEK 12 Solutions

---

meeting-rooms/YoungSeok-Choi.java

[YoungSeok-Choi] Week 13 solutions

---

counting-bits/byol-han.js

[byol-han] WEEK 14 solutions

---

construct-binary-tree-from-preorder-and-inorder-traversal/hoyeongkwak.ts
longest-palindromic-substring/hoyeongkwak.ts
rotate-image/hoyeongkwak.ts
subtree-of-another-tree/hoyeongkwak.ts

[hoyeongkwak] Week15 Solutions

---

contains-duplicate/Geegong.java
longest-consecutive-sequence/Geegong.java
top-k-frequent-elements/Geegong.java
two-sum/Geegong.java

[geegong] WEEK 01 solutions

---

contains-duplicate/jeongyunjae.py
house-robber/jeongyunjae.py
longest-consecutive-sequence/jeongyunjae.py
top-k-frequent-elements/jeongyunjae.py
two-sum/jeongyunjae.py

[jeongyunjae] WEEK 01 solutions

---

contains-duplicate/sooooo-an.ts
longest-consecutive-sequence/sooooo-an.ts
top-k-frequent-elements/sooooo-an.ts
two-sum/sooooo-an.ts

[sooooo-an] WEEK 01 solutions 

---

contains-duplicate/DaleSeo.rs

[DaleSeo] WEEK01 solutions

---

contains-duplicate/Lustellz.ts
two-sum/Lustellz.ts

[Lustellz] WEEK 01 solutions

---

valid-anagram/DaleSeo.rs

[DaleSeo] WEEK 02 solutions

---

number-of-1-bits/sonjh1217.swift
valid-palindrome/sonjh1217.swift

[sonjh1217] WEEK 03 solutions

---

number-of-1-bits/Kyojin-Hwang.js
valid-palindrome/Kyojin-Hwang.js

[Kyojin-Hwang] WEEK 03 solutions

---

combination-sum/s0ooo0k.java
decode-ways/s0ooo0k.java
maximum-subarray/Solution.java
maximum-subarray/s0ooo0k.java
number-of-1-bits/s0ooo0k.java
valid-palindrome/s0ooo0k.java

[s0ooo0k] WEEK 03 Solutions

---

valid-palindrome/DaleSeo.rs

[DaleSeo] WEEK 03 solutions

---

merge-two-sorted-lists/hi-rachel.js

[hi-rachel] WEEK 04 Solutions

---

merge-two-sorted-lists/Lustellz.ts

[Lustellz] WEEK 04 solution

---

coin-change/hoyeongkwak.java
find-minimum-in-rotated-sorted-array/hoyeongkwak.java
maximum-depth-of-binary-tree/hoyeongkwak.java
merge-two-sorted-lists/hoyeongkwak.java
word-search/hoyeongkwak.java

[hoyeongkwak] Week4 Solutions

---

group-anagrams/jangwonyoon.js

[jangwonyoon] weeks 5 Solutions

---

valid-parentheses/DaleSeo.rs

[DaleSeo] WEEK 06 solutions

---

course-schedule/yhkee0404.swift
invert-binary-tree/yhkee0404.rs
jump-game/yhkee0404.dart
merge-k-sorted-lists/yhkee0404.go
search-in-rotated-sorted-array/yhkee0404.scala

[yhkee0404] WEEK 10 solutions

---

invert-binary-tree/s0ooo0k.java
jump-game/s0ooo0k.java

[s0ooo0k] WEEK 10 Solutions

---

invert-binary-tree/sonjh1217.swift

[sonjh1217] WEEK 10 Solutions

---

binary-tree-maximum-path-sum/hyer0705.ts
graph-valid-tree/hyer0705.ts
merge-intervals/hyer0705.ts
missing-number/hyer0705.ts
reorder-list/hyer0705.ts

[hyer0705] WEEK 11 Solutions

---

missing-number/Lustellz.ts

[Lustellz] Week 11 solution
